"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

const DAYS = [["mon","Monday"],["tue","Tuesday"],["wed","Wednesday"],["thu","Thursday"],["fri","Friday"],["sat","Saturday"],["sun","Sunday"]] as const;
function message(v:any){return String(v?.message||v?.error||v||"Request failed").replace(/_/g," ");}
export default function RxSettingsPage(){
  const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [ok,setOk]=useState("");
  const [form,setForm]=useState<any>({acceptingRxOrders:true,supportsPickup:true,supportsDelivery:false,rxTimeZone:"Africa/Johannesburg",rxOrderPauseReason:"",rxOrderPauseUntil:"",rxOpeningHours:{}});
  async function load(){setError("");try{const r=await fetch("/api/careport/pharmacies/me/rx-availability",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw j;const a=j.availability||{};setData(a);setForm({acceptingRxOrders:a.acceptingRxOrders!==false,supportsPickup:a.supportsPickup!==false,supportsDelivery:Boolean(a.supportsDelivery),rxTimeZone:a.rxTimeZone||"Africa/Johannesburg",rxOrderPauseReason:a.rxOrderPauseReason||"",rxOrderPauseUntil:a.rxOrderPauseUntil?new Date(a.rxOrderPauseUntil).toISOString().slice(0,16):"",rxOpeningHours:a.rxOpeningHours||{}});}catch(e){setError(message(e));}}
  useEffect(()=>{void load();},[]);
  function dayWindow(day:string){const x=form.rxOpeningHours?.[day];const first=Array.isArray(x)?x[0]:x;return {open:first?.open||"",close:first?.close||""};}
  function setDay(day:string,key:"open"|"close",value:string){setForm((f:any)=>{const current=dayWindow.call({form:f},day);const next={...(f.rxOpeningHours||{})}; if(!value&&!current[key==="open"?"close":"open"]){delete next[day];}else next[day]=[{...current,[key]:value}]; return {...f,rxOpeningHours:next};});}
  async function save(){setBusy(true);setError("");setOk("");try{const body={...form,rxOrderPauseUntil:form.rxOrderPauseUntil?new Date(form.rxOrderPauseUntil).toISOString():null,rxOrderPauseReason:form.rxOrderPauseReason||null};const r=await fetch("/api/careport/pharmacies/me/rx-availability",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw j;setOk("Rx availability settings saved.");await load();}catch(e){setError(message(e));}finally{setBusy(false);}}
  const readiness=useMemo(()=>({kyc:data?.kycStatus==="APPROVED"&&!!data?.kycVerifiedAt,hours:Object.keys(form.rxOpeningHours||{}).length>0,timezone:!!form.rxTimeZone,pickup:!!form.supportsPickup}),[data,form]);
  return <main className="mx-auto max-w-5xl space-y-6">
    <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Canonical Rx control plane</p><h1 className="text-2xl font-semibold">Prescription availability</h1><p className="mt-1 text-sm text-slate-600">These settings control whether the pharmacy is selectable for new prescription quotes. Patient delivery stays disabled at canonical checkout until Wave C.</p></div><div className="flex gap-2"><Link href="/pharmacy" className="rounded-xl border px-3 py-2 text-sm">Dashboard</Link><Link href="/pharmacy/rx-catalogue" className="rounded-xl border px-3 py-2 text-sm">Rx catalogue</Link></div></header>
    {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{ok&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{ok}</div>}
    <section className="grid gap-3 md:grid-cols-4">{Object.entries(readiness).map(([k,v])=><div key={k} className="rounded-2xl border bg-white p-4"><div className={`text-lg font-semibold ${v?"text-emerald-700":"text-amber-700"}`}>{v?"Ready":"Needs setup"}</div><div className="text-xs capitalize text-slate-500">{k}</div></div>)}</section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="flex items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={form.acceptingRxOrders} onChange={e=>setForm({...form,acceptingRxOrders:e.target.checked})}/><div><div className="font-semibold">Accept new Rx orders</div><div className="text-xs text-slate-500">Turning this off removes the pharmacy from selectable new quotes.</div></div></label><label className="flex items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={form.supportsPickup} onChange={e=>setForm({...form,supportsPickup:e.target.checked})}/><div><div className="font-semibold">Pickup supported</div><div className="text-xs text-slate-500">Required for Wave AB canonical fulfilment.</div></div></label></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">IANA timezone<input value={form.rxTimeZone} onChange={e=>setForm({...form,rxTimeZone:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5" placeholder="Africa/Johannesburg"/></label><label className="text-sm font-medium">Pause until<input type="datetime-local" value={form.rxOrderPauseUntil} onChange={e=>setForm({...form,rxOrderPauseUntil:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label></div><label className="mt-4 block text-sm font-medium">Pause reason<input value={form.rxOrderPauseReason} onChange={e=>setForm({...form,rxOrderPauseReason:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5" placeholder="Optional operational reason"/></label>
    </section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Weekly Rx opening hours</h2><p className="mt-1 text-sm text-slate-500">One window per day is shown here; the API supports up to four validated windows per day.</p><div className="mt-4 space-y-2">{DAYS.map(([day,label])=>{const v=dayWindow(day);return <div key={day} className="grid grid-cols-[1fr_1fr_1fr] items-center gap-3 rounded-xl border p-3"><span className="text-sm font-medium">{label}</span><input type="time" value={v.open} onChange={e=>setDay(day,"open",e.target.value)} className="rounded-lg border px-2 py-1.5 text-sm"/><input type="time" value={v.close} onChange={e=>setDay(day,"close",e.target.value)} className="rounded-lg border px-2 py-1.5 text-sm"/></div>})}</div></section>
    <div className="flex justify-end"><button disabled={busy} onClick={save} className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save Rx availability"}</button></div>
  </main>;
}
