"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
function msg(v:any){return String(v?.message||v?.error||v||"Request failed").replace(/_/g," ");}
function money(c:number,cur="ZAR"){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:cur}).format((Number(c)||0)/100)}catch{return `${cur} ${((Number(c)||0)/100).toFixed(2)}`}}
export default function RxOrderPage({params}:{params:{orderId:string}}){const id=params.orderId;const [order,setOrder]=useState<any>(null);const [labels,setLabels]=useState<any>(null);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [note,setNote]=useState("");const [reason,setReason]=useState("");const [eta,setEta]=useState("20");
 async function load(){setError("");try{const r=await fetch(`/api/careport/pharmacies/me/orders/${encodeURIComponent(id)}/rx-review`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw j;setOrder(j.order);}catch(e){setError(msg(e));}}
 useEffect(()=>{void load();},[id]);
 async function review(action:string){setBusy(action);setError("");try{const r=await fetch(`/api/careport/pharmacies/me/orders/${encodeURIComponent(id)}/rx-review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reasonCode:reason||undefined,note:note||undefined})});const j=await r.json();if(!r.ok||!j.ok)throw j;await load();}catch(e){setError(msg(e));}finally{setBusy("");}}
 async function fulfil(action:string){setBusy(action);setError("");try{const r=await fetch(`/api/careport/pharmacies/me/orders/${encodeURIComponent(id)}/rx-fulfilment`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,preparationEtaMin:Number(eta)||undefined})});const j=await r.json();if(!r.ok||!j.ok)throw j;await load();}catch(e){setError(msg(e));}finally{setBusy("");}}
 async function loadLabels(reprint=false){setBusy("labels");setError("");try{const r=await fetch(`/api/careport/pharmacies/me/orders/${encodeURIComponent(id)}/rx-labels`,{method:reprint?"POST":"GET",headers:reprint?{"content-type":"application/json"}:undefined,body:reprint?"{}":undefined,cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw j;setLabels(j);}catch(e){setError(msg(e));}finally{setBusy("");}}
 if(!order)return <main className="p-6">{error?<div className="text-rose-700">{error}</div>:"Loading canonical Rx order…"}</main>;
 const reservation=order.rxReservation;const reviewState=order.rxPharmacistReview?.status||"PENDING";const payment=(order.payments||[])[0];
 return <main className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Canonical prescription fulfilment</p><h1 className="text-2xl font-semibold">Order {order.id}</h1><p className="mt-1 text-sm text-slate-500">Patient-identifiable clinical workflow. Delivery dispatch is not available in Wave AB.</p></div><Link href="/pharmacy/orders" className="rounded-xl border px-3 py-2 text-sm">Back to orders</Link></header>{error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="grid gap-3 md:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">Order</div><div className="font-semibold">{String(order.status).replace(/_/g," ")}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">Reservation</div><div className="font-semibold">{reservation?.status||"—"}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">Payment truth</div><div className="font-semibold">{payment?.status||"—"}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">Total</div><div className="font-semibold">{money(reservation?.totalCents||order.totalCents,reservation?.currency||order.currency)}</div></div></section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Prescription and reserved product truth</h2><div className="mt-4 space-y-3">{(reservation?.lines||[]).map((line:any)=>{const snap=line.productSnapshot||{};const sel=snap.selectedOption||{};return <div key={line.id} className="rounded-2xl border p-4"><div className="font-semibold">{sel.displayName||line.skuId}</div><div className="mt-1 text-sm text-slate-600">{[sel.brand,sel.strengthText,sel.dosageFormText,sel.packSize].filter(Boolean).join(" · ")}</div><div className="mt-2 text-xs text-slate-500">{line.requiredPacks} pack(s) · {money(line.grossCents,reservation.currency)} · SKU {line.skuId}</div></div>})}</div></section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Clinical gate</p><h2 className="text-lg font-semibold">Pharmacist review</h2></div><span className="rounded-full border px-3 py-1 text-xs font-semibold">{reviewState.replace(/_/g," ")}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={reason} onChange={e=>setReason(e.target.value)} className="rounded-xl border px-3 py-2" placeholder="Reason code (if needed)"/><input value={note} onChange={e=>setNote(e.target.value)} className="rounded-xl border px-3 py-2" placeholder="Clinical note / clarification"/></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void review("RELEASE")} disabled={!!busy} className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Release prescription</button><button onClick={()=>void review("CLARIFICATION_REQUIRED")} disabled={!!busy} className="rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Request clarification</button><button onClick={()=>void review("REJECT")} disabled={!!busy} className="rounded-xl border border-rose-200 px-4 py-2 text-sm font-semibold text-rose-700">Reject & refund/release</button></div><p className="mt-3 text-xs text-slate-500">Post-reservation arbitrary substitution is blocked. A different SKU requires a future governed reprice/reauthorisation flow.</p></section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Preparation</p><h2 className="text-lg font-semibold">Prepare, pack and release pickup</h2><div className="mt-4 flex flex-wrap items-end gap-2"><label className="text-sm">ETA minutes<input type="number" min="1" value={eta} onChange={e=>setEta(e.target.value)} className="ml-2 w-24 rounded-xl border px-3 py-2"/></label><button onClick={()=>void fulfil("START_PREPARING")} className="rounded-xl border px-3 py-2 text-sm font-semibold">Start preparing</button><button onClick={()=>void fulfil("SET_ETA")} className="rounded-xl border px-3 py-2 text-sm font-semibold">Set ETA</button><button onClick={()=>void fulfil("PACKING_COMPLETE")} className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Packing complete</button><button onClick={()=>void fulfil("READY_FOR_PICKUP")} className="rounded-xl bg-teal-700 px-3 py-2 text-sm font-semibold text-white">Ready for pickup</button><button onClick={()=>void fulfil("MARK_COLLECTED")} className="rounded-xl border px-3 py-2 text-sm font-semibold">Mark collected</button></div></section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Labels</p><h2 className="text-lg font-semibold">Actual-dispense and privacy-minimised labels</h2></div><div className="flex gap-2"><button onClick={()=>void loadLabels(false)} className="rounded-xl border px-3 py-2 text-sm">Preview</button><button onClick={()=>void loadLabels(true)} className="rounded-xl border px-3 py-2 text-sm">Reprint + audit</button></div></div>{labels&&<div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-semibold">Dispensing label</h3><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(labels.dispensingLabel||labels.dispensingLabels||labels.dispensing,null,2)}</pre></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-semibold">Outer pickup label</h3><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(labels.outerLabel||labels.outer,null,2)}</pre><p className="mt-2 text-xs text-slate-500">Outer labels deliberately exclude medicine/diagnosis details.</p></div></div>}</section>
 </main>;
}
