export type CarePortAttributeType =
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'multi_select'
  | 'unit_value';

export type CarePortAttributeTemplate = {
  key: string;
  label: string;
  type: CarePortAttributeType;
  required?: boolean;
  unitOptions?: string[];
  options?: string[];
  allowCustom?: boolean;
  examples?: string[];
};

export type CarePortCategoryTemplate = {
  key: string;
  label: string;
  productTypes: string[];
  subcategories: string[];
  attributes: string[];
  marketplaceDefault: boolean;
  prescriptionRequiredDefault: boolean;
  otcDefault?: boolean;
  notes?: string;
};

export const CAREPORT_TAXONOMY_VERSION = '2026.07.09-careport-global-marketplace-v1';

export const productTypes = [
  {
    key: 'MEDICATION',
    label: 'Prescription medication',
    description: 'Prescription-only medicines fulfilled only through a valid eRx or prescription workflow.',
    marketplaceDefault: false,
    prescriptionRequiredDefault: true,
    otcDefault: false,
  },
  {
    key: 'OTC_MEDICATION',
    label: 'OTC medication',
    description: 'Over-the-counter medicines that may be sold directly when local regulation permits.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: true,
  },
  {
    key: 'SUPPLEMENT',
    label: 'Vitamins & supplements',
    description: 'Vitamins, minerals, nutritional supplements and wellness products.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: true,
  },
  {
    key: 'MEDICAL_DEVICE',
    label: 'Medical device',
    description: 'Retail medical devices and healthcare equipment.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'PERSONAL_CARE',
    label: 'Personal care',
    description: 'General personal-care items sold by pharmacies.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'SKINCARE',
    label: 'Skincare',
    description: 'Dermatology, cosmetic, sunscreen and skin-health products.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'HAIRCARE',
    label: 'Haircare',
    description: 'Hair products, scalp products and grooming items.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'BABY_CARE',
    label: 'Baby care',
    description: 'Baby health, hygiene and care products.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'HOUSEHOLD',
    label: 'Household',
    description: 'Household and wellness-adjacent pharmacy merchandise.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
  {
    key: 'GENERAL_MERCHANDISE',
    label: 'General merchandise',
    description: 'Other pharmacy retail items such as bottles, utensils and non-clinical goods.',
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: false,
  },
];

export const standardOptions = {
  colours: [
    'Black',
    'White',
    'Blue',
    'Red',
    'Green',
    'Yellow',
    'Pink',
    'Purple',
    'Grey',
    'Silver',
    'Gold',
    'Rose gold',
    'Brown',
    'Beige',
    'Transparent',
    'Mixed',
    'Other',
  ],
  flavours: [
    'Unflavoured',
    'Mint',
    'Menthol',
    'Orange',
    'Lemon',
    'Berry',
    'Strawberry',
    'Cherry',
    'Grape',
    'Honey',
    'Vanilla',
    'Chocolate',
    'Rooibos honey',
    'Other',
  ],
  dosageForms: [
    'Tablet',
    'Capsule',
    'Caplet',
    'Syrup',
    'Suspension',
    'Drops',
    'Sachet',
    'Powder',
    'Cream',
    'Ointment',
    'Gel',
    'Spray',
    'Patch',
    'Inhaler',
    'Nebule',
    'Suppository',
    'Injection',
    'Solution',
    'Lotion',
    'Shampoo',
    'Soap',
    'Wipes',
    'Device',
    'Other',
  ],
  strengthUnits: [
    'mg',
    'mcg',
    'g',
    'mL',
    'mg/mL',
    'mg/5mL',
    'mcg/dose',
    'IU',
    '%',
    'mmol',
    'Other',
  ],
  packUnits: [
    'tablet',
    'capsule',
    'sachet',
    'bottle',
    'tube',
    'jar',
    'pump',
    'spray',
    'vial',
    'ampoule',
    'strip',
    'pair',
    'piece',
    'pack',
    'box',
    'mL',
    'L',
    'g',
    'kg',
    'Other',
  ],
  skinTypes: [
    'All skin types',
    'Dry',
    'Oily',
    'Combination',
    'Sensitive',
    'Acne-prone',
    'Eczema-prone',
    'Mature',
    'Baby skin',
    'Other',
  ],
  hairTypes: [
    'All hair types',
    'Dry hair',
    'Oily hair',
    'Curly hair',
    'Coily hair',
    'Straight hair',
    'Colour-treated hair',
    'Dandruff-prone scalp',
    'Sensitive scalp',
    'Other',
  ],
  materials: [
    'Plastic',
    'Glass',
    'Stainless steel',
    'Aluminium',
    'Silicone',
    'Cotton',
    'Latex-free',
    'Latex',
    'Ceramic',
    'Bamboo',
    'Mixed',
    'Other',
  ],
  ageBands: [
    'Adult',
    'Child',
    'Infant',
    'Newborn',
    'Teen',
    'Family',
    'All ages',
    'Other',
  ],
  regulatorySchedules: [
    'UNSCHEDULED',
    'OTC',
    'PHARMACY_ONLY',
    'S0',
    'S1',
    'S2',
    'S3',
    'S4',
    'S5',
    'S6',
    'CONTROLLED',
    'COUNTRY_SPECIFIC',
    'UNKNOWN',
  ],
  taxCategories: [
    'STANDARD',
    'ZERO_RATED',
    'EXEMPT',
    'REDUCED',
    'COUNTRY_SPECIFIC',
    'UNKNOWN',
  ],
};

export const attributeTemplates: Record<string, CarePortAttributeTemplate> = {
  brand: {
    key: 'brand',
    label: 'Brand',
    type: 'text',
    allowCustom: true,
    examples: ['Panado', 'Dis-Chem house brand', 'Cetaphil'],
  },
  manufacturer: {
    key: 'manufacturer',
    label: 'Manufacturer / supplier',
    type: 'text',
    allowCustom: true,
  },
  barcode: {
    key: 'barcode',
    label: 'Barcode / GTIN / EAN / UPC',
    type: 'text',
    allowCustom: true,
  },
  dosageForm: {
    key: 'dosageForm',
    label: 'Dosage form / format',
    type: 'select',
    options: standardOptions.dosageForms,
    allowCustom: true,
  },
  strength: {
    key: 'strength',
    label: 'Strength',
    type: 'unit_value',
    unitOptions: standardOptions.strengthUnits,
    allowCustom: true,
    examples: ['500 mg', '100 mg/5mL', '10 mcg/dose'],
  },
  packSize: {
    key: 'packSize',
    label: 'Pack size',
    type: 'unit_value',
    unitOptions: standardOptions.packUnits,
    allowCustom: true,
    examples: ['24 tablets', '100 mL', '500 g'],
  },
  flavour: {
    key: 'flavour',
    label: 'Flavour',
    type: 'select',
    options: standardOptions.flavours,
    allowCustom: true,
  },
  colour: {
    key: 'colour',
    label: 'Colour',
    type: 'select',
    options: standardOptions.colours,
    allowCustom: true,
  },
  size: {
    key: 'size',
    label: 'Size',
    type: 'text',
    allowCustom: true,
    examples: ['Small', 'Medium', 'Large', '750 mL', '100 mL'],
  },
  material: {
    key: 'material',
    label: 'Material',
    type: 'select',
    options: standardOptions.materials,
    allowCustom: true,
  },
  capacity: {
    key: 'capacity',
    label: 'Capacity / volume',
    type: 'unit_value',
    unitOptions: ['mL', 'L', 'g', 'kg', 'Other'],
    allowCustom: true,
    examples: ['500 mL', '750 mL', '1 L'],
  },
  skinType: {
    key: 'skinType',
    label: 'Skin type',
    type: 'select',
    options: standardOptions.skinTypes,
    allowCustom: true,
  },
  hairType: {
    key: 'hairType',
    label: 'Hair type',
    type: 'select',
    options: standardOptions.hairTypes,
    allowCustom: true,
  },
  ageBand: {
    key: 'ageBand',
    label: 'Age band',
    type: 'select',
    options: standardOptions.ageBands,
    allowCustom: true,
  },
  spf: {
    key: 'spf',
    label: 'SPF',
    type: 'number',
    allowCustom: true,
    examples: ['15', '30', '50'],
  },
  fragrance: {
    key: 'fragrance',
    label: 'Fragrance',
    type: 'select',
    options: ['Fragrance-free', 'Light fragrance', 'Fragranced', 'Other'],
    allowCustom: true,
  },
  lidType: {
    key: 'lidType',
    label: 'Lid type',
    type: 'select',
    options: ['Flip lid', 'Screw cap', 'Sports cap', 'Straw lid', 'Pump', 'No lid', 'Other'],
    allowCustom: true,
  },
  regulatedSchedule: {
    key: 'regulatedSchedule',
    label: 'Regulatory schedule',
    type: 'select',
    options: standardOptions.regulatorySchedules,
    allowCustom: true,
  },
};

export const categories: CarePortCategoryTemplate[] = [
  {
    key: 'pain_relief',
    label: 'Pain relief',
    productTypes: ['OTC_MEDICATION', 'MEDICATION'],
    subcategories: ['Headache', 'Fever', 'Muscle pain', 'Anti-inflammatory', 'Topical analgesic'],
    attributes: ['brand', 'barcode', 'dosageForm', 'strength', 'packSize', 'ageBand', 'regulatedSchedule'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: true,
    notes: 'Prescription-required schedules must remain locked behind eRx even if entered in this category.',
  },
  {
    key: 'cold_flu',
    label: 'Cold & flu',
    productTypes: ['OTC_MEDICATION', 'SUPPLEMENT'],
    subcategories: ['Cough', 'Sore throat', 'Nasal congestion', 'Flu relief', 'Immune support'],
    attributes: ['brand', 'barcode', 'dosageForm', 'strength', 'packSize', 'flavour', 'ageBand', 'regulatedSchedule'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: true,
  },
  {
    key: 'vitamins_supplements',
    label: 'Vitamins & supplements',
    productTypes: ['SUPPLEMENT'],
    subcategories: ['Multivitamins', 'Vitamin C', 'Vitamin D', 'Iron', 'Magnesium', 'Omega 3', 'Probiotics', 'Protein'],
    attributes: ['brand', 'barcode', 'dosageForm', 'strength', 'packSize', 'flavour', 'ageBand'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
    otcDefault: true,
  },
  {
    key: 'first_aid',
    label: 'First aid',
    productTypes: ['MEDICAL_DEVICE', 'PERSONAL_CARE'],
    subcategories: ['Bandages', 'Dressings', 'Antiseptics', 'Burn care', 'Gloves', 'Thermometers'],
    attributes: ['brand', 'barcode', 'size', 'packSize', 'material', 'ageBand'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'medical_devices',
    label: 'Medical devices',
    productTypes: ['MEDICAL_DEVICE'],
    subcategories: ['Blood pressure monitors', 'Thermometers', 'Nebulisers', 'Glucose meters', 'Pulse oximeters', 'Supports and braces'],
    attributes: ['brand', 'barcode', 'size', 'material', 'ageBand'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'skincare',
    label: 'Skincare',
    productTypes: ['SKINCARE', 'PERSONAL_CARE'],
    subcategories: ['Moisturisers', 'Cleansers', 'Sunscreen', 'Acne care', 'Dermocosmetics', 'Baby skincare'],
    attributes: ['brand', 'barcode', 'skinType', 'spf', 'fragrance', 'size', 'capacity', 'packSize'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'haircare',
    label: 'Haircare',
    productTypes: ['HAIRCARE', 'PERSONAL_CARE'],
    subcategories: ['Shampoo', 'Conditioner', 'Treatment', 'Scalp care', 'Styling', 'Hair accessories'],
    attributes: ['brand', 'barcode', 'hairType', 'fragrance', 'size', 'capacity', 'packSize'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'baby_care',
    label: 'Baby care',
    productTypes: ['BABY_CARE', 'SKINCARE', 'PERSONAL_CARE'],
    subcategories: ['Nappies', 'Wipes', 'Baby skincare', 'Feeding', 'Teething', 'Baby health'],
    attributes: ['brand', 'barcode', 'ageBand', 'size', 'packSize', 'fragrance', 'material'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'hydration_bottles',
    label: 'Hydration & bottles',
    productTypes: ['GENERAL_MERCHANDISE', 'HOUSEHOLD'],
    subcategories: ['Water bottles', 'Shakers', 'Travel mugs', 'Kids bottles'],
    attributes: ['brand', 'barcode', 'capacity', 'colour', 'material', 'lidType'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'home_kitchen',
    label: 'Home & kitchen',
    productTypes: ['HOUSEHOLD', 'GENERAL_MERCHANDISE'],
    subcategories: ['Kitchen utensils', 'Storage', 'Cleaning', 'General household'],
    attributes: ['brand', 'barcode', 'size', 'colour', 'material', 'packSize'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
  {
    key: 'general_merchandise',
    label: 'General pharmacy merchandise',
    productTypes: ['GENERAL_MERCHANDISE'],
    subcategories: ['Accessories', 'Seasonal', 'Wellness merchandise', 'Other'],
    attributes: ['brand', 'barcode', 'size', 'colour', 'material', 'packSize'],
    marketplaceDefault: true,
    prescriptionRequiredDefault: false,
  },
];

export const marketplaceRules = {
  patientPurchasableWhere: {
    isActive: true,
    marketplaceVisible: true,
    sellableOnline: true,
    prescriptionRequired: false,
  },
  prescriptionOnlyRule:
    'Items marked prescriptionRequired=true must not be directly purchasable from the patient marketplace and should only be fulfilled through a valid eRx/prescription flow.',
  otcRule:
    'OTC items may be patient-purchasable only where local regulation allows and the pharmacy has marked the SKU active, sellableOnline and marketplaceVisible.',
  customValueRule:
    'Pharmacies may enter custom attribute values through variantAttributes or attributes; admin catalogue governance can later normalise them to canonical global values.',
};

export const normalisationStatuses = [
  'RAW_PHARMACY_SUPPLIED',
  'MAPPED_TO_TEMPLATE',
  'ADMIN_VERIFIED',
  'GLOBAL_CATALOGUE_MATCHED',
  'REJECTED',
];

export const catalogueSources = [
  'PHARMACY_SUPPLIED',
  'CSV_IMPORT',
  'ADMIN_CREATED',
  'GLOBAL_CATALOGUE',
  'PARTNER_FEED',
  'NAPPI',
  'RXNORM',
  'GTIN',
];

export const csvHeaders = [
  'name',
  'productType',
  'category',
  'subcategory',
  'brand',
  'manufacturer',
  'barcode',
  'skuCode',
  'drugCode',
  'nappi',
  'rxnorm',
  'dosageForm',
  'strength',
  'packSize',
  'variantGroupKey',
  'variantName',
  'colour',
  'flavour',
  'size',
  'material',
  'capacity',
  'skinType',
  'hairType',
  'ageBand',
  'regulatedSchedule',
  'otc',
  'prescriptionRequired',
  'marketplaceVisible',
  'sellableOnline',
  'price',
  'priceCents',
  'currency',
  'stockOnHand',
  'reservedStock',
  'lowStockThreshold',
  'maxOrderQty',
  'ageRestricted',
  'taxCategory',
];

export function carePortCatalogueTaxonomy() {
  return {
    ok: true,
    version: CAREPORT_TAXONOMY_VERSION,
    productTypes,
    categories,
    attributeTemplates,
    standardOptions,
    marketplaceRules,
    normalisationStatuses,
    catalogueSources,
    csvHeaders,
    ui: {
      allowCustomAttributeValues: true,
      customValueTargetFields: ['variantAttributes', 'attributes'],
      recommendedCreateFlow: [
        'Search global catalogue first',
        'Select product type and category',
        'Apply category attribute template',
        'Choose standard values where available',
        'Enter custom values where necessary',
        'Set pharmacy-specific price and stock',
        'Apply OTC / prescription-required / marketplace visibility rules',
        'Save SKU and flag unmapped items for catalogue governance',
      ],
    },
  };
}
