import type { Metadata } from "next";
import { site } from "@/lib/site";

export type SeoRoute = {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  priority: number;
  changeFrequency:
    | "always"
    | "hourly"
    | "daily"
    | "weekly"
    | "monthly"
    | "yearly"
    | "never";
};

export const siteUrl = site.url.replace(/\/+$/, "");

export function absoluteUrl(path = "/"): string {
  if (path.startsWith("http://") || path.startsWith("https://")) return path;
  return `${siteUrl}${path.startsWith("/") ? path : `/${path}`}`;
}

export const coreKeywords = [
  // Brand and entity terms
  "Ambulant+",
  "Ambulant Plus",
  "Ambulant+ South Africa",
  "Cloven Technology",
  "Cloven Technology Impilo",
  "Contactless Medicine",
  "contactless medicine",
  "Contactless Medicine platform",
  "contactless healthcare",
  "contactless healthcare South Africa",
  "personal health management software",
  "personal health management platform",
  "digital health South Africa",
  "health technology South Africa",
  "HealthTech South Africa",
  "MedTech South Africa",

  // Telemedicine / virtual care alternatives
  "telemedicine South Africa",
  "telehealth South Africa",
  "virtual healthcare South Africa",
  "virtual care South Africa",
  "online doctor South Africa",
  "online doctor consultation",
  "virtual doctor consultation",
  "doctor booking platform",
  "doctor booking South Africa",
  "find a doctor",
  "find a doctor online",
  "book a doctor online",
  "instant care",
  "instant consultation",
  "primary care",
  "primary care platform",
  "online primary care",
  "virtual primary care",
  "doctor on demand",
  "doctor on the go",
  "remote consultation",
  "remote clinical consultation",
  "clinician-led virtual care",

  // Remote monitoring and vitals
  "remote monitoring",
  "remote patient monitoring",
  "remote patient monitoring South Africa",
  "continuous remote monitoring",
  "continuous patient monitoring",
  "continuous vitals",
  "continuous vital signs monitoring",
  "remote vitals",
  "remote vital signs",
  "home vitals monitoring",
  "vitals monitoring app",
  "vital signs monitoring",
  "remote health monitoring",
  "home health monitoring",
  "chronic disease monitoring",
  "chronic care monitoring",
  "post-discharge monitoring",
  "preventive monitoring",
  "preventive care",
  "preventative care",
  "early intervention healthcare",
  "holistic care",
  "precision medicine",
  "predictive medicine",
  "personalised healthcare",
  "personalized healthcare",

  // IoMT and integrated medical hardware
  "IoMT",
  "iomt",
  "Internet of Medical Things",
  "Internet of Medical Things platform",
  "IoMT healthcare",
  "IoMT healthcare platform",
  "integrated medical hardware",
  "integrated medical devices",
  "connected medical devices",
  "connected health devices",
  "connected care platform",
  "medical device integration",
  "home medical devices",
  "remote diagnostic devices",
  "clinical devices for telemedicine",
  "device-supported telemedicine",
  "device-supported virtual care",
  "medical hardware integration",

  // Supported devices
  "Health Monitor",
  "remote health monitor",
  "6 in 1 health monitor",
  "six in one health monitor",
  "blood pressure monitoring",
  "remote blood pressure monitoring",
  "SpO2 monitoring",
  "oxygen saturation monitoring",
  "remote glucose monitoring",
  "temperature monitoring",
  "ECG screening",
  "home ECG",
  "Digital Stethoscope",
  "digital stethoscope",
  "remote stethoscope",
  "digital auscultation",
  "remote auscultation",
  "heart sound recording",
  "lung sound recording",
  "HD Otoscope",
  "digital otoscope",
  "remote otoscope",
  "ear imaging",
  "remote ear examination",
  "NexRing",
  "smart ring health monitor",
  "health ring",
  "wearable health ring",
  "sleep SpO2",
  "temperature variation",
  "fertility temperature tracking",
  "wearable fertility tracking",

  // Clinical and care data
  "clinical data",
  "patient clinical data",
  "structured clinical data",
  "clinical data platform",
  "health records",
  "electronic health records",
  "patient health passport",
  "health passport",
  "daily health score",
  "patient profile",
  "medical history",
  "care summary",
  "session summary",
  "clinical notes",
  "care pathway",
  "care coordination",
  "continuity of care",
  "longitudinal health data",
  "longitudinal monitoring",
  "clinical intelligence",

  // Diagnostics and fulfilment
  "home diagnostics",
  "home diagnostics South Africa",
  "home phlebotomy",
  "home phlebotomy South Africa",
  "home blood draw",
  "home blood collection",
  "specimen collection",
  "laboratory coordination",
  "lab result routing",
  "diagnostic testing at home",
  "MedReach",
  "CarePort",
  "pharmacy fulfilment",
  "medicine delivery",
  "medicine delivery South Africa",
  "prescription delivery",
  "ePrescription delivery",
  "eRx delivery",
  "last mile medicine delivery",
  "medication fulfilment",
  "medication adherence",
  "medication adherence scoring",
  "camera verification medication",
  "camera verified medication adherence",
  "pill reminders",
  "medication reminders",

  // Payer / medical aid / sponsor
  "medical aid digital health",
  "medical aid wellness platform",
  "medical aid remote monitoring",
  "medical aid preventive care",
  "medical aid claims reconciliation",
  "medical aid member engagement",
  "medical aid rewards",
  "HMO preventive care",
  "HMO remote monitoring",
  "corporate wellness platform",
  "employer health programme",
  "sponsor-funded healthcare",
  "healthcare rewards platform",
  "wellness rewards platform",
  "claims preflight",
  "coverage preflight",
  "medical aid eligibility verification",
  "payment status verification",
  "member lifetime value",
  "preventive care ROI",

  // Care centres and specific pathways
  "women's health virtual care",
  "ladies health app",
  "fertility tracking",
  "fertility monitoring",
  "fertility consultation online",
  "antenatal care support",
  "pregnancy care app",
  "paediatric telemedicine",
  "child health app",
  "men's health virtual care",
  "gentlemen's health",
  "family health platform",
  "multi-user consultation",
  "multidisciplinary virtual consultation",
];

export const seoRoutes: SeoRoute[] = [
  {
    path: "/",
    title: "Ambulant+ | Contactless Medicine Platform in South Africa",
    description:
      "Ambulant+ is a Contactless Medicine platform connecting patients, clinicians, connected devices, home diagnostics, pharmacy fulfilment and preventive-care intelligence in one governed ecosystem.",
    keywords: [
      ...coreKeywords,
      "Contactless Medicine platform",
      "Ambulant+ South Africa",
      "personal health management software",
      "remote consultations with vitals",
      "clinician-led connected care",
    ],
    priority: 1,
    changeFrequency: "weekly",
  },
  {
    path: "/platform",
    title: "Platform | Ambulant+ Contactless Medicine Infrastructure",
    description:
      "Explore the Ambulant+ platform architecture for patient access, clinician workflows, connected-device review, diagnostics coordination, pharmacy fulfilment and governance-aware intelligence.",
    keywords: [
      "Contactless Medicine infrastructure",
      "healthcare platform architecture",
      "patient clinician platform",
      "connected care platform",
      "Ambulant+ platform",
    ],
    priority: 0.9,
    changeFrequency: "monthly",
  },
  {
    path: "/features",
    title: "Features | Connected Care, Devices, Reminders and Health Passport",
    description:
      "Ambulant+ features include connected device workflows, clinician-led consultation, health passport, reminders, self-check, MedReach diagnostics, CarePort fulfilment and InsightCore intelligence.",
    keywords: [
      "remote patient monitoring features",
      "continuous remote monitoring",
      "continuous vitals",
      "remote vitals",
      "connected care features",
      "contactless medicine features",
      "IoMT features",
      "iomt features",
      "integrated medical hardware",
      "home IoMT use",
      "clinical data platform",
      "health passport",
      "daily health score",
      "self-check health app",
      "medication reminders",
      "camera verification medication",
      "virtual care with devices",
      "digital auscultation",
      "digital stethoscope consultation",
      "home diagnostics",
      "pharmacy fulfilment",
      "preventive care",
      "holistic care",
      "precision medicine",
      "InsightCore intelligence"
    ],
    priority: 0.92,
    changeFrequency: "monthly",
  },
  {
    path: "/devices",
    title: "Devices | Health Monitor, Digital Stethoscope, HD Otoscope and NexRing",
    description:
      "Ambulant+ focuses on a defined connected-device ecosystem: Health Monitor, Digital Stethoscope, HD Otoscope and NexRing for supported remote-care workflows.",
    keywords: [
      "Health Monitor",
      "remote health monitor",
      "6 in 1 health monitor",
      "Digital Stethoscope",
      "digital stethoscope",
      "remote stethoscope",
      "digital auscultation",
      "remote auscultation",
      "HD Otoscope",
      "digital otoscope",
      "remote otoscope",
      "NexRing",
      "smart ring health monitor",
      "connected medical devices",
      "integrated medical hardware",
      "IoMT devices South Africa",
      "iomt devices South Africa",
      "Internet of Medical Things devices",
      "remote patient monitoring devices",
      "continuous vitals devices",
      "home vitals devices",
      "remote diagnostic devices",
      "clinical data devices",
      "device-supported telemedicine",
      "virtual consultation devices",
      "telemedicine with stethoscope",
      "telemedicine with otoscope",
      "telemedicine with vitals"
    ],
    priority: 0.9,
    changeFrequency: "monthly",
  },
  {
    path: "/patients",
    title: "Patients | Protected Contactless Medicine Workspace",
    description:
      "Ambulant+ gives patients a protected workspace for virtual consultations, connected-device pathways, medication support, health records, reports, bookings and care-network access.",
    keywords: [
      "patient health app South Africa",
      "personal health management software",
      "virtual doctor consultation",
      "online doctor South Africa",
      "doctor booking platform",
      "find a doctor online",
      "book a doctor online",
      "instant care",
      "instant consultation",
      "primary care app",
      "remote consultation with vitals",
      "remote vitals",
      "home vitals monitoring",
      "patient health passport",
      "daily health score",
      "home monitoring app",
      "connected medical devices at home",
      "IoMT patient app",
      "iomt patient app",
      "clinical data for patients",
      "health records app",
      "medication reminders",
      "camera verified medication adherence",
      "CarePort medicine delivery",
      "MedReach home diagnostics",
      "medical aid readiness",
      "wallet health app"
    ],
    priority: 0.9,
    changeFrequency: "monthly",
  },
  {
    path: "/patients/getting-started",
    title: "Getting Started | Ambulant+ Patient Setup Guide",
    description:
      "Learn how patients begin with Ambulant+: profile setup, bookings, connected devices, medical-aid readiness, medication support and governed care pathways.",
    keywords: [
      "Ambulant+ patient setup",
      "how to use Ambulant+",
      "create patient account",
      "connect health devices",
      "connect IoMT devices",
      "link medical hardware",
      "book virtual doctor",
      "book online doctor",
      "find a doctor",
      "doctor booking",
      "patient onboarding",
      "medical aid setup",
      "wallet setup",
      "device setup",
      "Health Monitor setup",
      "Digital Stethoscope setup",
      "HD Otoscope setup",
      "NexRing setup",
      "remote vitals setup",
      "home monitoring setup",
      "CarePort setup",
      "MedReach setup"
    ],
    priority: 0.82,
    changeFrequency: "monthly",
  },
  {
    path: "/centres/ladies-health",
    title: "Ladies’ Health Centre | Women’s Health Pathways on Ambulant+",
    description:
      "Ambulant+ Ladies’ Health supports women’s health pathways, wellness prompts, fertility-relevant signals, clinician review and connected-care coordination.",
    keywords: [
      "women's health South Africa",
      "ladies health app",
      "fertility tracking",
      "virtual gynaecology consultation",
      "NexRing fertility",
    ],
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    path: "/centres/paediatric",
    title: "Paediatric Centre | Child Health Pathways on Ambulant+",
    description:
      "Ambulant+ Paediatric Centre supports parent-led child health access, paediatric consultation pathways, care records, reminders and governed escalation.",
    keywords: [
      "paediatric telemedicine South Africa",
      "child health app",
      "virtual paediatric consultation",
      "family health monitoring",
    ],
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    path: "/centres/antenatal",
    title: "Antenatal Centre | Pregnancy Support and Connected Care",
    description:
      "Ambulant+ Antenatal Centre supports pregnancy care coordination, appointment readiness, clinical review pathways, wellness prompts and care-team visibility.",
    keywords: [
      "antenatal care South Africa",
      "pregnancy telemedicine",
      "virtual obstetric consultation",
      "pregnancy monitoring support",
    ],
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    path: "/centres/gentlemens-health",
    title: "Gentlemen’s Health Centre | Men’s Health Pathways on Ambulant+",
    description:
      "Ambulant+ Gentlemen’s Health supports men’s health pathways, screening prompts, remote clinical access, wellness tracking and follow-up coordination.",
    keywords: [
      "men's health South Africa",
      "gentlemen's health app",
      "virtual men's health consultation",
      "preventive men's health",
    ],
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    path: "/clinicians",
    title: "Clinicians | Governed Remote Practice with Connected Devices",
    description:
      "Ambulant+ helps clinicians deliver remote care with patient context, connected-device review, structured documentation, MedReach diagnostics, CarePort fulfilment and governance-aware workflows.",
    keywords: [
      "clinician remote practice",
      "doctor telemedicine platform",
      "remote consultation platform for doctors",
      "connected device review",
      "HPCSA digital health",
    ],
    priority: 0.9,
    changeFrequency: "monthly",
  },
  {
    path: "/clinicians/onboarding",
    title: "Clinician Onboarding | Join the Ambulant+ Clinical Network",
    description:
      "Learn how clinicians onboard to Ambulant+, including profile readiness, training, compliance checks, workspace access and device-supported remote-care preparation.",
    keywords: [
      "clinician onboarding",
      "join Ambulant+",
      "remote doctor platform South Africa",
      "Contactless Medicine training",
    ],
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    path: "/clients",
    title: "Medical Aids, HMOs and Corporate Sponsors | Ambulant+",
    description:
      "Ambulant+ helps medical aids, HMOs, insurers, employers and sponsors support preventive care, remote monitoring, adherence visibility, home diagnostics and governed care-network access.",
    keywords: [
      "medical aid digital health",
      "medical aid remote monitoring",
      "medical aid preventive care",
      "medical aid wellness platform",
      "medical aid member engagement",
      "medical aid claims reconciliation",
      "HMO preventive care",
      "HMO remote monitoring",
      "corporate wellness platform",
      "remote patient monitoring for insurers",
      "continuous remote monitoring",
      "continuous vitals",
      "remote vitals",
      "member clinical data",
      "clinical data platform",
      "member health intelligence",
      "chronic disease prevention",
      "medication adherence scoring",
      "camera verification medication",
      "eRx auto sync",
      "home diagnostics for medical aids",
      "pharmacy fulfilment for medical aids",
      "wellness rewards platform",
      "preventive care ROI",
      "member lifetime value",
      "claims preflight",
      "coverage preflight",
      "payment status verification",
      "precision medicine for payers"
    ],
    priority: 0.95,
    changeFrequency: "monthly",
  },
  {
    path: "/medreach",
    title: "MedReach | Home Diagnostics and Laboratory Operations",
    description:
      "MedReach coordinates home phlebotomy, specimen collection, laboratory handover, chain-of-custody visibility and result-routing workflows inside Ambulant+.",
    keywords: [
      "home phlebotomy South Africa",
      "home diagnostics",
      "laboratory coordination",
      "specimen collection",
      "MedReach",
    ],
    priority: 0.88,
    changeFrequency: "monthly",
  },
  {
    path: "/medreach/labs",
    title: "MedReach for Labs | Laboratory Coordination and Result Routing",
    description:
      "MedReach helps laboratories participate in governed home-diagnostics workflows, specimen handover, catalogue readiness and result-routing coordination.",
    keywords: [
      "laboratory digital health",
      "lab result routing",
      "home blood draw labs",
      "specimen handover",
    ],
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/medreach/phlebotomists",
    title: "MedReach for Phlebotomists | Home Draw Operations",
    description:
      "MedReach supports phlebotomist workflows for home draws, patient verification, specimen labelling, handover readiness and diagnostic task visibility.",
    keywords: [
      "phlebotomist home draw",
      "home blood collection",
      "diagnostic task workflow",
      "MedReach phlebotomy",
    ],
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/careport",
    title: "CarePort | Pharmacy Fulfilment and Medicine Delivery Operations",
    description:
      "CarePort coordinates pharmacy fulfilment, rider dispatch, medicine handover, delivery tracking, proof-of-delivery and patient updates inside Ambulant+.",
    keywords: [
      "pharmacy fulfilment",
      "medicine delivery South Africa",
      "eRx delivery",
      "CarePort",
      "medication adherence",
    ],
    priority: 0.88,
    changeFrequency: "monthly",
  },
  {
    path: "/careport/pharmacies",
    title: "CarePort for Pharmacies | eRx Fulfilment and Dispatch Readiness",
    description:
      "CarePort helps pharmacies manage prescription fulfilment, catalogue visibility, dispatch handover, proof-of-delivery and medicine-continuity workflows.",
    keywords: [
      "pharmacy dispatch platform",
      "prescription fulfilment",
      "eRx pharmacy workflow",
      "medicine delivery pharmacy",
    ],
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/careport/riders",
    title: "CarePort for Riders | Medicine Delivery and Handover Workflow",
    description:
      "CarePort supports delivery-rider workflows for medicine pickup, handover, tracking, patient updates and proof-of-delivery inside governed fulfilment operations.",
    keywords: [
      "medicine delivery riders",
      "pharmacy rider workflow",
      "proof of delivery healthcare",
      "CarePort riders",
    ],
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/insightcore",
    title: "InsightCore | Healthcare Intelligence and Programme Visibility",
    description:
      "InsightCore gives programme teams visibility across adherence signals, remote monitoring trends, utilisation, risk indicators, care pathways and operational performance.",
    keywords: [
      "healthcare intelligence",
      "programme visibility",
      "medical aid analytics",
      "remote monitoring analytics",
      "preventive care intelligence",
    ],
    priority: 0.86,
    changeFrequency: "monthly",
  },
  {
    path: "/operations",
    title: "Operations | Clinical, Diagnostic and Fulfilment Coordination",
    description:
      "Ambulant+ operations coordinate clinical workflows, MedReach diagnostics, CarePort pharmacy fulfilment, onboarding, support and governance escalation.",
    keywords: [
      "healthcare operations",
      "clinical workflow coordination",
      "diagnostics operations",
      "pharmacy fulfilment operations",
    ],
    priority: 0.82,
    changeFrequency: "monthly",
  },
  {
    path: "/partnerships",
    title: "Partnerships | Build Contactless Medicine Programmes with Ambulant+",
    description:
      "Partner with Ambulant+ to build governed Contactless Medicine programmes across clinicians, medical aids, HMOs, employers, pharmacies, laboratories, phlebotomy networks, technology partners and community care access points.",
    keywords: [
      "Contactless Medicine partnership",
      "Contactless Medicine partnerships South Africa",
      "healthcare partnerships South Africa",
      "digital health partnerships",
      "MedTech partnerships South Africa",
      "telemedicine partnership",
      "telehealth partnership",
      "virtual care partnership",
      "remote patient monitoring partnership",
      "remote monitoring partnership",
      "continuous remote monitoring partnership",
      "IoMT partnership",
      "Internet of Medical Things partnership",
      "connected medical device partnership",
      "medical device integration partnership",
      "integrated medical hardware partnership",
      "medical aid partnership",
      "medical aid digital health partnership",
      "HMO partnership",
      "health insurance digital health partnership",
      "corporate wellness partnership",
      "employer health programme partnership",
      "preventive care partnership",
      "chronic care partnership",
      "pharmacy delivery partnership",
      "pharmacy fulfilment partnership",
      "eRx fulfilment partnership",
      "medicine delivery partnership",
      "CarePort partnership",
      "laboratory diagnostics partnership",
      "home phlebotomy partnership",
      "home diagnostics partnership",
      "MedReach partnership",
      "phlebotomy network partnership",
      "clinical network partnership",
      "doctor network partnership",
      "specialist network partnership",
      "community healthcare partnership",
      "healthcare access partnership",
      "airport clinic partnership",
      "mall clinic partnership",
      "workplace clinic partnership",
      "connected healthcare ecosystem",
      "governed healthcare platform",
      "healthcare programme deployment",
      "healthcare innovation partnership",
      "digital health South Africa",
      "MedTech South Africa",
    ],
    priority: 0.88,
    changeFrequency: "monthly",
  },
  {
    path: "/bookings",
    title: "Bookings | Schedule Ambulant+ Demos and Partnership Sessions",
    description:
      "Book Ambulant+ demos, partner sessions, clinical workflow discussions, medical-aid briefings, device pathway reviews and Contactless Medicine discovery calls.",
    keywords: [
      "book Ambulant+ demo",
      "Contactless Medicine demo",
      "healthcare platform booking",
      "digital health demo South Africa",
    ],
    priority: 0.82,
    changeFrequency: "monthly",
  },
  {
    path: "/demos",
    title: "Demos | Experience Ambulant+ Contactless Medicine Workflows",
    description:
      "Explore Ambulant+ demos covering remote consultation, connected devices, home diagnostics, pharmacy fulfilment, medical-aid readiness and governed care operations.",
    keywords: [
      "Ambulant+ demo",
      "remote patient monitoring demo",
      "IoMT demo",
      "Contactless Medicine exhibition",
    ],
    priority: 0.82,
    changeFrequency: "monthly",
  },
  {
    path: "/resources",
    title: "Resources | Contactless Medicine Guides, IoMT Setup and Remote Care Knowledge Library",
    description:
      "Ambulant+ resources for Contactless Medicine, remote patient monitoring, IoMT device setup, Health Monitor workflows, Digital Stethoscope auscultation, NexRing guidance, MedReach diagnostics, CarePort medicine fulfilment, medical aids, clinicians and patients.",
    keywords: [
      "Contactless Medicine resources",
      "remote patient monitoring guides",
      "remote care guides South Africa",
      "IoMT device setup guide",
      "Health Monitor setup guide",
      "Digital Stethoscope workflow guide",
      "digital auscultation guide",
      "remote auscultation guide",
      "HD Otoscope workflow guide",
      "NexRing setup guide",
      "NexRing wearing guide",
      "remote vitals monitoring",
      "continuous vitals monitoring",
      "home diagnostics guide",
      "virtual consultation device workflow",
      "medical aid remote monitoring guide",
      "medical aid preventive care resources",
      "CarePort medicine delivery guide",
      "CarePort prescription fulfilment",
      "MedReach home phlebotomy guide",
      "MedReach lab workflow",
      "clinician onboarding Contactless Medicine",
      "patient remote monitoring setup",
      "remote care training South Africa",
      "Contactless Medicine knowledge library",
    ],
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    path: "/innovation",
    title: "Innovation | The Ambulant+ Contactless Medicine Thesis",
    description:
      "Ambulant+ innovation focuses on clinician-led connected care, home diagnostics, pharmacy continuity, preventive intelligence and governed health-system infrastructure.",
    keywords: [
      "healthcare innovation South Africa",
      "Contactless Medicine innovation",
      "digital health innovation",
      "preventive healthcare platform",
    ],
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    path: "/research-and-development",
    title: "Research and Development | Connected Care and Workflow Evidence",
    description:
      "Ambulant+ research and development focuses on connected-care workflows, device-supported consultation, diagnostics operations, fulfilment logistics and governance design.",
    keywords: [
      "digital health research",
      "connected care research",
      "IoMT research",
      "remote patient monitoring research",
    ],
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    path: "/ecosystem",
    title: "Ecosystem | Ambulant+, MedReach, CarePort and InsightCore",
    description:
      "Understand the Ambulant+ ecosystem across patient access, clinician workspaces, MedReach diagnostics, CarePort fulfilment, InsightCore intelligence and Cloven Technology Impilo.",
    keywords: [
      "Ambulant+ ecosystem",
      "Cloven Technology Impilo",
      "MedReach",
      "CarePort",
      "InsightCore",
    ],
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    path: "/use-cases",
    title: "Use Cases | Contactless Medicine Pathways for Real-World Care",
    description:
      "Explore Ambulant+ use cases for chronic care, preventive monitoring, medical aids, home diagnostics, pharmacy continuity, remote practice and care-centre pathways.",
    keywords: [
      "Contactless Medicine use cases",
      "remote monitoring use cases",
      "chronic care prevention",
      "home diagnostics use cases",
    ],
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    path: "/security",
    title: "Security | Protected Workspaces and Governance-Aware Access",
    description:
      "Ambulant+ is designed around protected workspaces, role-based access, data minimisation, auditability, environment separation and governance-aware healthcare operations.",
    keywords: [
      "healthcare data security",
      "POPIA healthcare",
      "role-based access healthcare",
      "secure telemedicine platform",
    ],
    priority: 0.76,
    changeFrequency: "monthly",
  },
  {
    path: "/compliance",
    title: "Compliance | Clinical Governance, Privacy and Operational Controls",
    description:
      "Ambulant+ compliance language supports privacy, clinical-governance workflows, audit-friendly records, careful claims and controlled healthcare operations.",
    keywords: [
      "healthcare compliance South Africa",
      "clinical governance",
      "POPIA compliance",
      "digital health compliance",
    ],
    priority: 0.76,
    changeFrequency: "monthly",
  },
  {
    path: "/clinical-disclaimer",
    title: "Clinical Disclaimer | Ambulant+",
    description:
      "Read the Ambulant+ clinical disclaimer covering emergency limitations, professional judgement, device-supported workflows and responsible use of Contactless Medicine.",
    keywords: [
      "Ambulant+ clinical disclaimer",
      "telemedicine disclaimer",
      "remote care disclaimer",
    ],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/privacy",
    title: "Privacy Policy | Ambulant+",
    description:
      "Read the Ambulant+ privacy policy for information about personal data, health-related information, consent-aware sharing and privacy responsibilities.",
    keywords: [
      "Ambulant+ privacy policy",
      "health data privacy",
      "POPIA privacy",
    ],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/terms",
    title: "Terms and Conditions | Ambulant+",
    description:
      "Read the Ambulant+ terms and conditions for platform access, responsible use, service boundaries and operational rules.",
    keywords: [
      "Ambulant+ terms",
      "Contactless Medicine terms",
      "platform terms",
    ],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/faq",
    title: "FAQ | Ambulant+ Contactless Medicine Questions",
    description:
      "Find answers to common Ambulant+ questions about Contactless Medicine, patient access, clinicians, devices, MedReach, CarePort and platform workflows.",
    keywords: [
      "Ambulant+ FAQ",
      "Contactless Medicine questions",
      "telemedicine FAQ",
      "remote monitoring FAQ",
    ],
    priority: 0.74,
    changeFrequency: "monthly",
  },
  {
    path: "/contact",
    title: "Contact | Speak to Ambulant+",
    description:
      "Contact Ambulant+ for demos, partnerships, medical-aid discussions, clinician onboarding, patient support, MedReach, CarePort and Contactless Medicine enquiries.",
    keywords: [
      "contact Ambulant+",
      "Ambulant+ support",
      "book Contactless Medicine demo",
      "medical aid partnership contact",
    ],
    priority: 0.82,
    changeFrequency: "monthly",
  },
];

export function getSeoRoute(path: string): SeoRoute {
  return seoRoutes.find((route) => route.path === path) ?? seoRoutes[0];
}

export function buildPageMetadata(routePath: string, overrides?: Partial<SeoRoute>): Metadata {
  const route = { ...getSeoRoute(routePath), ...overrides };
  const canonical = absoluteUrl(route.path);
  const image = absoluteUrl("/og/ambulant-og.webp");

  return {
    metadataBase: new URL(siteUrl),
    title: route.title,
    description: route.description,
    keywords: Array.from(new Set([...coreKeywords, ...route.keywords])),
    alternates: {
      canonical,
    },
    openGraph: {
      title: route.title,
      description: route.description,
      url: canonical,
      siteName: site.name,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: "Ambulant+ Contactless Medicine platform",
        },
      ],
      locale: "en_ZA",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: route.title,
      description: route.description,
      images: [image],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
  };
}

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": absoluteUrl("/#organization"),
    name: site.name,
    legalName: site.parentCompany,
    url: siteUrl,
    logo: absoluteUrl("/brand/ambulant-logo-full.png"),
    image: absoluteUrl("/og/ambulant-og.webp"),
    description:
      "Ambulant+ is a Contactless Medicine ecosystem by Cloven Technology Impilo, connecting patient access, clinician workflows, connected medical devices, MedReach diagnostics, CarePort fulfilment and InsightCore intelligence.",
    telephone: site.phone,
    email: site.generalEmail,
    address: {
      "@type": "PostalAddress",
      streetAddress:
        "Block D FF, Saint Andrews Office Park, 0B Meadowbrook Lane, Epsom Downs",
      addressLocality: "Bryanston",
      addressRegion: "Gauteng",
      postalCode: "2152",
      addressCountry: "ZA",
    },
    parentOrganization: {
      "@type": "Organization",
      name: site.parentCompany,
      email: site.corporateEmail,
    },
    brand: site.brandFamily.map((brand) => ({
      "@type": "Brand",
      name: brand.name,
      description: brand.summary,
    })),
    areaServed: [
      {
        "@type": "Country",
        name: "South Africa",
      },
    ],
    knowsAbout: [
      // Category ownership
      "Contactless Medicine",
      "contactless medicine",
      "Contactless Medicine platform",
      "Contactless healthcare",
      "Digital health infrastructure",
      "Health technology",
      "MedTech",
      "Healthcare software",
      "Personal health management",
      "Personal health management software",
      "Personal health management platform",

      // Telemedicine replacement / comparison terms
      "Telemedicine",
      "Telehealth",
      "Virtual care",
      "Virtual healthcare",
      "Online doctor consultation",
      "Online doctor",
      "Doctor booking",
      "Find a doctor",
      "Book a doctor online",
      "Instant care",
      "Instant consultation",
      "Primary care",
      "Online primary care",
      "Virtual primary care",
      "Clinician-led virtual care",
      "Remote consultation",
      "Remote clinical consultation",

      // Remote monitoring and vitals
      "Remote monitoring",
      "Remote patient monitoring",
      "Continuous remote monitoring",
      "Continuous patient monitoring",
      "Continuous vitals",
      "Continuous vital signs monitoring",
      "Remote vitals",
      "Remote vital signs",
      "Home vitals monitoring",
      "Vital signs monitoring",
      "Remote health monitoring",
      "Home health monitoring",
      "Chronic disease monitoring",
      "Chronic care monitoring",
      "Post-discharge monitoring",
      "Preventive monitoring",
      "Preventive care",
      "Preventative care",
      "Early intervention healthcare",
      "Holistic care",
      "Precision medicine",
      "Predictive medicine",
      "Personalised healthcare",
      "Personalized healthcare",

      // IoMT and hardware terms
      "Internet of Medical Things",
      "IoMT",
      "iomt",
      "IoMT healthcare",
      "IoMT healthcare platform",
      "Integrated medical hardware",
      "Integrated medical devices",
      "Connected medical devices",
      "Connected health devices",
      "Connected care platform",
      "Medical device integration",
      "Home medical devices",
      "Remote diagnostic devices",
      "Clinical devices for telemedicine",
      "Device-supported telemedicine",
      "Device-supported virtual care",
      "Medical hardware integration",

      // Supported device ecosystem
      "Health Monitor",
      "Remote Health Monitor",
      "6 in 1 Health Monitor",
      "Blood pressure monitoring",
      "Remote blood pressure monitoring",
      "SpO2 monitoring",
      "Oxygen saturation monitoring",
      "Remote glucose monitoring",
      "Temperature monitoring",
      "ECG screening",
      "Home ECG",
      "Digital Stethoscope",
      "digital stethoscope",
      "Remote stethoscope",
      "Digital auscultation",
      "Remote auscultation",
      "Heart sound recording",
      "Lung sound recording",
      "HD Otoscope",
      "Digital otoscope",
      "Remote otoscope",
      "Ear imaging",
      "Remote ear examination",
      "NexRing",
      "Smart ring health monitor",
      "Health ring",
      "Wearable health ring",
      "Sleep SpO2",
      "Temperature variation",
      "Fertility temperature tracking",
      "Wearable fertility tracking",

      // Clinical data and care records
      "Clinical data",
      "Patient clinical data",
      "Structured clinical data",
      "Clinical data platform",
      "Health records",
      "Electronic health records",
      "Patient health passport",
      "Health passport",
      "Daily health score",
      "Patient profile",
      "Medical history",
      "Care summary",
      "Session summary",
      "Clinical notes",
      "Care pathway",
      "Care coordination",
      "Continuity of care",
      "Longitudinal health data",
      "Longitudinal monitoring",
      "Clinical intelligence",

      // Diagnostics and laboratory operations
      "Home diagnostics",
      "Home phlebotomy",
      "Home blood draw",
      "Home blood collection",
      "Specimen collection",
      "Laboratory coordination",
      "Lab result routing",
      "Diagnostic testing at home",
      "MedReach",
      "Phlebotomy workflow",
      "Specimen chain of custody",
      "Laboratory result routing",

      // Pharmacy and medication continuity
      "CarePort",
      "Pharmacy fulfilment",
      "Pharmacy fulfillment",
      "Medicine delivery",
      "Prescription delivery",
      "ePrescription delivery",
      "eRx delivery",
      "Last mile medicine delivery",
      "Medication fulfilment",
      "Medication fulfillment",
      "Medication adherence",
      "Medication adherence scoring",
      "Camera verification medication",
      "Camera-verified medication adherence",
      "Pill reminders",
      "Medication reminders",
      "eRx auto sync",
      "Prescription fulfilment",

      // Medical aid, HMO and payer terms
      "Medical aid digital health",
      "Medical aid wellness platform",
      "Medical aid remote monitoring",
      "Medical aid preventive care",
      "Medical aid claims reconciliation",
      "Medical aid member engagement",
      "Medical aid rewards",
      "HMO preventive care",
      "HMO remote monitoring",
      "Corporate wellness platform",
      "Employer health programme",
      "Sponsor-funded healthcare",
      "Healthcare rewards",
      "Healthcare rewards platform",
      "Wellness rewards platform",
      "Claims preflight",
      "Coverage preflight",
      "Medical aid eligibility verification",
      "Payment status verification",
      "Member lifetime value",
      "Preventive care ROI",
      "Claims reconciliation",
      "Programme visibility",
      "Payer intelligence",

      // Care centres and patient pathways
      "Women's health virtual care",
      "Ladies health app",
      "Fertility tracking",
      "Fertility monitoring",
      "Fertility consultation online",
      "Antenatal care support",
      "Pregnancy care app",
      "Paediatric telemedicine",
      "Child health app",
      "Men's health virtual care",
      "Gentlemen's health",
      "Family health platform",
      "Multi-user consultation",
      "Multidisciplinary virtual consultation",

      // Governance and safety positioning
      "Clinical governance",
      "Healthcare governance",
      "Role-based access healthcare",
      "Consent-aware data sharing",
      "Healthcare privacy",
      "POPIA healthcare",
      "Secure healthcare platform",
      "Clinical workflow design",
      "Audit-ready healthcare operations",
      "Governed digital health workflows",
    ],
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "customer support",
        telephone: site.phone,
        email: site.supportEmail,
        areaServed: "ZA",
        availableLanguage: ["en"],
      },
      {
        "@type": "ContactPoint",
        contactType: "sales",
        telephone: site.phone,
        email: site.salesEmail,
        areaServed: "ZA",
        availableLanguage: ["en"],
      },
      {
        "@type": "ContactPoint",
        contactType: "demo bookings",
        telephone: site.phone,
        email: site.demoEmail,
        areaServed: "ZA",
        availableLanguage: ["en"],
      },
    ],
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": absoluteUrl("/#website"),
    name: site.name,
    url: siteUrl,
    publisher: {
      "@id": absoluteUrl("/#organization"),
    },
    inLanguage: "en-ZA",
    description:
      "Ambulant+ provides information about Contactless Medicine, remote patient monitoring, connected medical devices, home diagnostics, pharmacy fulfilment, patient access, clinician workflows and medical-aid preventive-care infrastructure.",
  };
}

export function softwareApplicationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": absoluteUrl("/#software"),
    name: site.name,
    applicationCategory: "HealthApplication",
    operatingSystem: "Web, iOS, Android",
    url: siteUrl,
    image: absoluteUrl("/og/ambulant-og.webp"),
    description:
      "Ambulant+ is a Contactless Medicine platform for patient access, clinician-led remote consultation, connected-device review, MedReach diagnostics, CarePort fulfilment and InsightCore programme visibility.",
    publisher: {
      "@id": absoluteUrl("/#organization"),
    },
    offers: {
      "@type": "Offer",
      category: "Digital health platform",
      availability: "https://schema.org/PreOrder",
    },
  };
}

export function breadcrumbJsonLd(
  items: Array<{
    name: string;
    path: string;
  }>,
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}