"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
function msg(v:any){return String(v?.message||v?.error||v||"Request failed").replace(/_/g," ");}
function money(c:number,cur="ZAR"){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:cur}).format((Number(c)||0)/100)}catch{return `${cur} ${((Number(c)||0)/100).toFixed(2)}`}}
export default function RxCataloguePage(){const [items,setItems]=useState<any[]>([]);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [q,setQ]=useState("");
 async function load(){setError("");try{const r=await fetch(`/api/careport/pharmacies/me/inventory?active=true&prescriptionRequired=true&limit=300&q=${encodeURIComponent(q)}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw j;setItems(j.items||[]);}catch(e){setError(msg(e));}}
 useEffect(()=>{void load();},[]);
 function change(id:string,key:string,value:any){setItems(xs=>xs.map(x=>x.id===id?{...x,[key]:value}:x));}
 async function save(x:any){setBusy(x.id);setError("");try{const body={rxPriceBasis:x.rxPriceBasis||null,rxDispenseUnit:x.rxDispenseUnit||null,rxUnitsPerPack:x.rxUnitsPerPack?Number(x.rxUnitsPerPack):null,rxTaxRateBps:x.rxTaxRateBps!==null&&x.rxTaxRateBps!==""?Number(x.rxTaxRateBps):null,rxPriceIncludesTax:x.rxPriceIncludesTax!==false,medicalAidClaimable:Boolean(x.medicalAidClaimable)};const r=await fetch(`/api/careport/pharmacies/me/inventory/${encodeURIComponent(x.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw j;await load();}catch(e){setError(msg(e));}finally{setBusy("");}}
 return <main className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Rx commercial truth</p><h1 className="text-2xl font-semibold">Checkout-ready medicine catalogue</h1><p className="mt-1 text-sm text-slate-600">Canonical checkout fails closed until pack basis, dispense unit, units per pack and tax metadata are explicit.</p></div><div className="flex gap-2"><Link href="/pharmacy" className="rounded-xl border px-3 py-2 text-sm">Dashboard</Link><Link href="/pharmacy/inventory" className="rounded-xl border px-3 py-2 text-sm">All inventory</Link></div></header>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search medicine" className="flex-1 rounded-xl border px-3 py-2"/><button onClick={load} className="rounded-xl border px-4 py-2 text-sm font-semibold">Search</button></div><div className="mt-5 overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="p-2">Medicine</th><th>Price</th><th>Basis</th><th>Dispense unit</th><th>Units/pack</th><th>VAT bps</th><th>Tax incl.</th><th>Medical aid</th><th></th></tr></thead><tbody>{items.map(x=>{const ready=x.rxPriceBasis==="PACK"&&x.rxDispenseUnit&&Number(x.rxUnitsPerPack)>0&&x.rxTaxRateBps!==null;return <tr key={x.id} className="border-t align-top"><td className="p-2"><div className="font-medium">{x.name}</div><div className={`mt-1 text-xs ${ready?"text-emerald-700":"text-amber-700"}`}>{ready?"Checkout ready":"Metadata incomplete"}</div></td><td>{money(x.priceCents,x.currency)}</td><td><select value={x.rxPriceBasis||""} onChange={e=>change(x.id,"rxPriceBasis",e.target.value)} className="rounded-lg border px-2 py-1.5"><option value="">—</option><option value="PACK">PACK</option></select></td><td><input value={x.rxDispenseUnit||""} onChange={e=>change(x.id,"rxDispenseUnit",e.target.value)} className="w-28 rounded-lg border px-2 py-1.5" placeholder="tablet"/></td><td><input type="number" min="1" value={x.rxUnitsPerPack??""} onChange={e=>change(x.id,"rxUnitsPerPack",e.target.value)} className="w-24 rounded-lg border px-2 py-1.5"/></td><td><input type="number" min="0" max="10000" value={x.rxTaxRateBps??""} onChange={e=>change(x.id,"rxTaxRateBps",e.target.value)} className="w-24 rounded-lg border px-2 py-1.5"/></td><td><input type="checkbox" checked={x.rxPriceIncludesTax!==false} onChange={e=>change(x.id,"rxPriceIncludesTax",e.target.checked)}/></td><td><input type="checkbox" checked={Boolean(x.medicalAidClaimable)} onChange={e=>change(x.id,"medicalAidClaimable",e.target.checked)}/></td><td><button disabled={busy===x.id} onClick={()=>void save(x)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Save</button></td></tr>})}</tbody></table></div>{!items.length&&<div className="p-8 text-center text-sm text-slate-500">No prescription medicines found.</div>}</section></main>}
