'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { uploadManagedFinanceDocument } from '@/lib/managed-finance-document-upload';

type Row = Record<string, any>;
const money = (c: any) => new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format((Number(c)||0)/100);
const date = (v:any) => v ? new Date(v).toLocaleDateString('en-ZA',{year:'numeric',month:'short',day:'2-digit'}) : '—';
async function api(path:string, init?:RequestInit) { const r=await fetch(path,{cache:'no-store',...init,headers:{'content-type':'application/json',...(init?.headers||{})}}); const j=await r.json().catch(()=>({})); if(!r.ok||j?.ok===false) throw new Error(j?.error||'Request failed'); return j; }
const input='rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm';
const button='rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40';

export default function PayrollPage(){
 const [q,setQ]=useState(''); const [profiles,setProfiles]=useState<Row[]>([]); const [selectedId,setSelectedId]=useState(''); const [history,setHistory]=useState<Row|null>(null); const [selectedEntitlements,setSelectedEntitlements]=useState<string[]>([]); const [partial,setPartial]=useState<Record<string,string>>({}); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const [payout,setPayout]=useState<Row|null>(null); const [newWorker,setNewWorker]=useState({displayName:'',email:'',engagementType:'CASUAL',startDate:'',baseSalary:''}); const [paymentReference,setPaymentReference]=useState(''); const [proof,setProof]=useState<File|null>(null);
 const selected=profiles.find(x=>x.id===selectedId)||null;
 const loadProfiles=useCallback(async()=>{ try{const j=await api('/api/enterprise-finance/staff-payroll/profiles?limit=500&q='+encodeURIComponent(q)); setProfiles(j.items||[]); if(!selectedId&&j.items?.length) setSelectedId(j.items[0].id);}catch(e:any){setMsg(e.message)} },[q,selectedId]);
 useEffect(()=>{void loadProfiles()},[loadProfiles]);
 const loadHistory=useCallback(async(id:string)=>{if(!id){setHistory(null);return;} try{const j=await api('/api/enterprise-finance/staff-payroll/history?payrollProfileId='+encodeURIComponent(id)); setHistory(j); setSelectedEntitlements([]);}catch(e:any){ if(String(e.message).includes('not_found')) setHistory(null); else setMsg(e.message);} },[]);
 useEffect(()=>{void loadHistory(selectedId)},[selectedId,loadHistory]);
 const entitlements:Row[]=history?.entitlements||[]; const compensation:Row[]=history?.compensationHistory||[];
 const outstanding=useMemo(()=>entitlements.reduce((s,x)=>s+(Number(x.remainingCents)||0),0),[entitlements]);
 async function mutate(body:Row){setBusy(true);setMsg('');try{const j=await api('/api/enterprise-finance/staff-payroll/history',{method:'POST',body:JSON.stringify(body)});setHistory(j);setSelectedEntitlements([]);setMsg('Saved. Historical payroll authority refreshed.');}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function rebuild(){if(!selectedId)return;await mutate({action:'rebuild',payrollProfileId:selectedId});}
 async function reconcile(state:string){if(!selectedId||!selectedEntitlements.length)return; const settlements=state==='PARTIALLY_SETTLED'?selectedEntitlements.map(id=>({entitlementId:id,amountHistoricallySettledCents:Math.round(Number(partial[id]||0)*100)})):undefined; await mutate({action:'reconcile',payrollProfileId:selectedId,entitlementIds:selectedEntitlements,settlementState:state,settlements,lock:true,reference:'Legacy payroll reconciliation'});}
 async function createWorker(){setBusy(true);try{await api('/api/enterprise-finance/staff-payroll/profiles',{method:'POST',body:JSON.stringify({staffDisplayName:newWorker.displayName,staffEmail:newWorker.email||null,engagementType:newWorker.engagementType,employmentType:newWorker.engagementType,startDate:newWorker.startDate,baseSalaryCents:Math.round(Number(newWorker.baseSalary||0)*100),payFrequency:'monthly',payrollStatus:'active',approvalStatus:'approved'})});setNewWorker({displayName:'',email:'',engagementType:'CASUAL',startDate:'',baseSalary:''});await loadProfiles();setMsg('Workforce/payroll record created without granting an Admin login.');}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function loadPayout(){if(!selectedId)return;try{setPayout(await api('/api/enterprise-finance/staff-payroll/payout?payrollProfileId='+encodeURIComponent(selectedId)))}catch(e:any){setMsg(e.message)}}
 async function preparePayslip(){if(!selectedId||!entitlements.length)return; const period=entitlements[entitlements.length-1]; const arrearsIds=selectedEntitlements.filter(id=>id!==period.id); const awards=(payout?.commissions||[]).filter((x:Row)=>x.status==='APPROVED').map((x:Row)=>x.id); setBusy(true);try{const j=await api('/api/enterprise-finance/staff-payroll/payout',{method:'POST',body:JSON.stringify({action:'prepare_payslip',payrollProfileId:selectedId,payrollPeriodId:period.payrollPeriodId,arrearsEntitlementIds:arrearsIds,commissionAwardIds:awards})});setMsg(`Payslip ${j.payslip?.payslipNumber||''} prepared: ${money(j.payslip?.netPayCents)}.`);await loadPayout();}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function markPaid(slip:Row){if(!proof||!paymentReference)return setMsg('Payment reference and proof of payment are required.');setBusy(true);try{const uploaded=await uploadManagedFinanceDocument({file:proof,purpose:'proof-of-payment'});await api('/api/enterprise-finance/staff-payroll/payout',{method:'POST',body:JSON.stringify({action:'mark_payslip_paid',payslipId:slip.id,paymentReference,proofOfPaymentObjectKey:uploaded.objectKey,paymentMethod:'manual'})});setMsg('Payslip payment closed, arrears allocations reconciled and commissions marked paid.');setProof(null);setPaymentReference('');await loadPayout();await loadHistory(selectedId);}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="mx-auto max-w-[1500px] space-y-6 p-6">
  <header><div className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Enterprise Finance</div><h1 className="mt-2 text-3xl font-black text-slate-950">Payroll, historical reconciliation & payouts</h1><p className="mt-2 max-w-4xl text-sm text-slate-600">Select a workforce member independently of arrears, reconstruct salary month-by-month from effective employment history, reconcile legacy settlements, then compose auditable payslips with arrears and commissions.</p></header>
  {msg&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm">{msg}</div>}
  <section className="grid gap-4 rounded-2xl border p-4 lg:grid-cols-6"><input className={input+' lg:col-span-2'} placeholder="Search name, email, Staff ID, payroll no." value={q} onChange={e=>setQ(e.target.value)}/><select className={input+' lg:col-span-4'} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select staff/workforce</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.staffName} · {p.engagementType} · {p.hasAdminLogin?'Admin-linked':'payee only'}</option>)}</select></section>
  <section className="rounded-2xl border p-4"><h2 className="font-bold">Add temporary / casual / commission-only worker</h2><div className="mt-3 grid gap-3 md:grid-cols-5"><input className={input} placeholder="Full name" value={newWorker.displayName} onChange={e=>setNewWorker({...newWorker,displayName:e.target.value})}/><input className={input} placeholder="Email (optional)" value={newWorker.email} onChange={e=>setNewWorker({...newWorker,email:e.target.value})}/><select className={input} value={newWorker.engagementType} onChange={e=>setNewWorker({...newWorker,engagementType:e.target.value})}>{['TEMPORARY','CASUAL','CONTRACTOR','INTERN','COMMISSION_ONLY','FIXED_TERM','PERMANENT'].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="date" value={newWorker.startDate} onChange={e=>setNewWorker({...newWorker,startDate:e.target.value})}/><input className={input} type="number" placeholder="Monthly salary R" value={newWorker.baseSalary} onChange={e=>setNewWorker({...newWorker,baseSalary:e.target.value})}/></div><button className={button+' mt-3'} disabled={busy||!newWorker.displayName||!newWorker.startDate} onClick={createWorker}>Create workforce payee</button></section>
  {selected&&<section className="grid gap-4 md:grid-cols-4">{[['Workforce',selected.staffName],['Engagement',selected.engagementType],['Current base',money(selected.baseSalaryCents)],['Historical arrears',money(outstanding)]].map(([a,b])=><div key={a} className="rounded-2xl border p-4"><div className="text-xs font-bold uppercase text-slate-500">{a}</div><div className="mt-2 text-xl font-bold">{b}</div></div>)}</section>}
  {selected&&<section className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Effective-dated compensation & monthly entitlements</h2><p className="text-sm text-slate-600">Rebuild never invents a missing effective date; mismatches are surfaced as warnings.</p></div><button className={button} disabled={busy} onClick={rebuild}>Rebuild from employment inception</button></div>{(history?.warnings||[]).map((w:any,i:number)=><div key={i} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{typeof w==='string'?w:JSON.stringify(w)}</div>)}<div className="mt-4 grid gap-2 md:grid-cols-3">{compensation.map(c=><div key={c.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{date(c.effectiveFrom)}</b>{c.effectiveTo?` → ${date(c.effectiveTo)}`:' → present'}<div>{money(c.baseSalaryCents)} / {c.payFrequency}</div><div className="text-xs text-slate-500">{c.changeType||c.sourceType}</div></div>)}</div>
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500">{['','Period','Rate / segments','Gross','Legacy settled','Paid later','Remaining','Legacy state','Locked','Partial R'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{entitlements.map(e=><tr key={e.id} className="border-b align-top"><td className="p-2"><input type="checkbox" checked={selectedEntitlements.includes(e.id)} disabled={!!e.lockedAt} onChange={()=>setSelectedEntitlements(v=>v.includes(e.id)?v.filter(x=>x!==e.id):[...v,e.id])}/></td><td className="p-2">{date(e.periodStartsAt)}–{date(e.periodEndsAt)}</td><td className="p-2">{(e.segments||[]).map((s:Row)=><div key={s.id}>{money(s.salaryRateCents)} · {s.eligibleDayCount}/{s.periodDayCount}d</div>)}</td><td className="p-2 font-semibold">{money(e.grossEntitlementCents)}</td><td className="p-2">{money(e.amountHistoricallySettledCents)}</td><td className="p-2">{money(e.postReconciliationPaidCents)}</td><td className="p-2 font-semibold">{money(e.remainingCents)}</td><td className="p-2">{e.settlementState}</td><td className="p-2">{e.lockedAt?'Locked':'Open'}</td><td className="p-2"><input className={input+' w-28'} type="number" disabled={!!e.lockedAt} value={partial[e.id]||''} onChange={x=>setPartial({...partial,[e.id]:x.target.value})}/></td></tr>)}</tbody></table></div>
   <div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={busy||!selectedEntitlements.length} onClick={()=>reconcile('FULLY_SETTLED')}>Lock selected fully settled</button><button className={button} disabled={busy||!selectedEntitlements.length} onClick={()=>reconcile('UNPAID')}>Lock selected unpaid</button><button className={button} disabled={busy||!selectedEntitlements.length} onClick={()=>reconcile('PARTIALLY_SETTLED')}>Lock selected partial</button></div></section>}
  {selected&&<section className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold">Payslip & payout cycle</h2><p className="text-sm text-slate-600">Base salary + selected historical arrears + approved commissions − deductions = payable amount.</p></div><button className={button} onClick={loadPayout}>Load payout state</button></div>{payout&&<><div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={busy||!entitlements.length} onClick={preparePayslip}>Prepare latest-period payslip</button><input className={input} placeholder="Bank / transfer reference" value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/><input className={input} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setProof(e.target.files?.[0]||null)}/></div><div className="mt-4 space-y-2">{(payout.payslips||[]).map((s:Row)=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><b>{s.payslipNumber||s.id}</b> · {s.status}<div className="text-sm">Net {money(s.netPayCents)} · arrears {money(s.arrearsPaidCents)} · commission {money(s.commissionCents)}</div></div>{s.status!=='paid'&&<button className={button} disabled={busy} onClick={()=>markPaid(s)}>Record full payment</button>}</div>)}</div></>}</section>}
 </main>;
}
