"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
function text(v:any){return String(v?.message||v?.error||v||"Request failed").replace(/_/g," ");}
export default function RxEventsPage(){const [events,setEvents]=useState<any[]>([]);const [connected,setConnected]=useState(false);const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/careport/pharmacies/me/rx-events?limit=100",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw j;setEvents(j.events||[]);}catch(e){setError(text(e));}}
 useEffect(()=>{void load();const es=new EventSource("/api/careport/pharmacies/me/rx-events/stream");es.addEventListener("connected",()=>setConnected(true));es.addEventListener("rx-event",(e:any)=>{try{const x=JSON.parse(e.data);setEvents(old=>[x,...old.filter(v=>v.id!==x.id)].slice(0,100));}catch{}});es.onerror=()=>setConnected(false);return()=>es.close();},[]);
 async function ack(id:string){const r=await fetch("/api/careport/pharmacies/me/rx-events",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[id]})});if(r.ok)setEvents(xs=>xs.map(x=>x.id===id?{...x,acknowledgedAt:new Date().toISOString()}:x));}
 return <main className="mx-auto max-w-5xl space-y-6"><header className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Durable Rx event truth</p><h1 className="text-2xl font-semibold">Prescription operations feed</h1><p className="mt-1 text-sm text-slate-600">Real-time transport is supplemental. Every event below is persisted before notification delivery.</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${connected?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{connected?"Live":"Reconnecting"}</span><Link href="/pharmacy" className="rounded-xl border px-3 py-2 text-sm">Dashboard</Link></div></header>{error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<section className="space-y-3">{events.map(e=><article key={e.id} className={`rounded-2xl border bg-white p-4 ${e.acknowledgedAt?"opacity-70":"border-teal-200"}`}><div className="flex flex-col gap-2 md:flex-row md:justify-between"><div><div className="font-semibold">{String(e.kind).replace(/_/g," ")}</div><div className="text-xs text-slate-500">Order {e.orderId} · {new Date(e.createdAt).toLocaleString()}</div><pre className="mt-2 whitespace-pre-wrap text-xs text-slate-600">{JSON.stringify(e.payload||{},null,2)}</pre></div>{!e.acknowledgedAt&&<button onClick={()=>void ack(e.id)} className="h-fit rounded-xl border px-3 py-2 text-xs font-semibold">Acknowledge</button>}</div></article>)}{!events.length&&<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">No Rx events yet.</div>}</section></main>}
