// apps/clinician-app/app/consults/discharge/page.tsx
'use client';

import React, { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import ReferralPanelEnhanced from '@/components/SessionConclusions';

type FormState = {
  noteType: 'none' | 'sick' | 'fitness';
  diagnosis: string;
  plan: string;
  notes: string;
  referral?: string;
};

function DischargeContent() {
  const searchParams = useSearchParams();

  const encounterId =
    searchParams?.get('encounterId') ||
    searchParams?.get('encounter') ||
    searchParams?.get('id') ||
    undefined;

  const clinicianId =
    searchParams?.get('clinicianId') ||
    searchParams?.get('clinician') ||
    'clinician-local-001';

  const [form, setForm] = useState<FormState>({
    noteType: 'none',
    diagnosis: '',
    plan: '',
    notes: '',
    referral: '',
  });

  // Autopopulate from SessionConclusions in localStorage
  useEffect(() => {
    if (!encounterId) return;

    try {
      const raw = localStorage.getItem(`sfu-session-conclusions:${encounterId}`);
      if (!raw) return;

      const draft = JSON.parse(raw) as {
        dxQuery?: string;
        plan?: string;
        notes?: string;
      };

      setForm((f) => ({
        ...f,
        diagnosis: draft.dxQuery || '',
        plan: draft.plan || '',
        notes: draft.notes || '',
      }));
    } catch {
      // Keep page usable if the local draft is malformed.
    }
  }, [encounterId]);


  // Create printable HTML and open print dialog
  function generatePrintableDoc(title: string, contentHtml: string) {
    const printWindow = window.open('', '_blank', 'noopener,noreferrer');

    if (!printWindow) {
      alert('Unable to open print window. Please check popup blocker.');
      return;
    }

    const style = `
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial;
          padding: 24px;
          color: #111;
        }
        h1 {
          font-size: 20px;
          margin-bottom: 8px;
        }
        .meta {
          margin-bottom: 12px;
          font-size: 13px;
          color: #333;
        }
        .section {
          margin-top: 12px;
        }
        .label {
          font-weight: 600;
          margin-bottom: 4px;
        }
        pre {
          white-space: pre-wrap;
          font-family: inherit;
        }
        .footer {
          margin-top: 28px;
          font-size: 12px;
          color: #666;
        }
      </style>
    `;

    printWindow.document.open();
    printWindow.document.write(`
      <!doctype html>
      <html>
        <head>
          <title>${title}</title>
          ${style}
        </head>
        <body>
          <h1>${title}</h1>
          <div class="meta">
            <div>Clinician ID: ${clinicianId || '—'}</div>
            <div>Encounter ID: ${encounterId || '—'}</div>
            <div>Generated: ${new Date().toLocaleString()}</div>
          </div>

          ${contentHtml}

          <div class="footer">Generated by Ambulant / Discharge Module</div>
        </body>
      </html>
    `);
    printWindow.document.close();

    // Give the window a tiny moment to render, then call print.
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 250);
  }

  function submit() {
    const docTitle =
      form.noteType === 'sick'
        ? 'Sick Note'
        : form.noteType === 'fitness'
          ? 'Fitness Certificate'
          : 'Clinical Note';

    const contentHtml = `
      <div class="section">
        <div class="label">Diagnosis</div>
        <pre>${form.diagnosis || '—'}</pre>
      </div>

      <div class="section">
        <div class="label">Plan</div>
        <pre>${form.plan || '—'}</pre>
      </div>

      <div class="section">
        <div class="label">Notes</div>
        <pre>${form.notes || '—'}</pre>
      </div>

      <div class="section">
        <div class="label">Referral</div>
        <pre>${form.referral || '—'}</pre>
      </div>
    `;

    generatePrintableDoc(docTitle, contentHtml);
  }

  return (
    <main className="p-6 space-y-3">
      <h2 className="text-lg font-semibold">Discharge / Schedule Follow-up / Refer</h2>

      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <label className="space-y-1">
          <div className="text-sm font-medium">Document Type</div>

          <select
            value={form.noteType}
            onChange={(e) =>
              setForm((f) => ({
                ...f,
                noteType: e.target.value as FormState['noteType'],
              }))
            }
            className="border rounded p-2"
          >
            <option value="none">Clinical Note (no certificate)</option>
            <option value="sick">Sick Note</option>
            <option value="fitness">Fitness Certificate</option>
          </select>
        </label>

        <label className="space-y-1">
          <div className="text-sm font-medium">Diagnosis</div>

          <input
            value={form.diagnosis}
            onChange={(e) =>
              setForm((f) => ({
                ...f,
                diagnosis: e.target.value,
              }))
            }
            className="border rounded p-2 w-full"
            placeholder="Diagnosis / Impression"
          />
        </label>

        <label className="space-y-1 md:col-span-2">
          <div className="text-sm font-medium">Plan</div>

          <textarea
            value={form.plan}
            onChange={(e) =>
              setForm((f) => ({
                ...f,
                plan: e.target.value,
              }))
            }
            className="border rounded p-2 w-full"
            placeholder="Plan / Treatment / Follow-up"
            rows={3}
          />
        </label>

        <label className="space-y-1 md:col-span-2">
          <div className="text-sm font-medium">Notes</div>

          <textarea
            value={form.notes}
            onChange={(e) =>
              setForm((f) => ({
                ...f,
                notes: e.target.value,
              }))
            }
            className="border rounded p-2 w-full"
            placeholder="Clinical notes, observations..."
            rows={4}
          />
        </label>

        <label className="space-y-1 md:col-span-2">
          <div className="text-sm font-medium">Referral</div>

          <textarea
            value={form.referral || ''}
            onChange={(e) =>
              setForm((f) => ({
                ...f,
                referral: e.target.value,
              }))
            }
            className="border rounded p-2 w-full"
            placeholder="Referral details, receiving clinician/service, reason for referral..."
            rows={3}
          />
        </label>

        <div className="md:col-span-2">
          <ReferralPanelEnhanced clinicianId={clinicianId} />
        </div>
      </div>

      <div className="flex gap-2">
        <button
          onClick={submit}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
          type="button"
        >
          Generate PDF / Print
        </button>

        <button
          onClick={() => {
            if (!encounterId) return;

            localStorage.setItem(
              `sfu-discharge:${encounterId}`,
              JSON.stringify(form),
            );

            alert('Saved locally.');
          }}
          className="px-4 py-2 border rounded"
          type="button"
        >
          Save Draft
        </button>
      </div>
    </main>
  );
}

export default function Discharge() {
  return (
    <Suspense fallback={null}>
      <DischargeContent />
    </Suspense>
  );
}
