'use client';
import { useCallback, useEffect, useState } from 'react';
type Account = { id: string; email: string; role: string; actorRefId: string; status: string; version: number; credentialReady: boolean };
export default function PartnerAccess() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [reason, setReason] = useState(''); const [verified, setVerified] = useState(false); const [message, setMessage] = useState(''); const [setup, setSetup] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { const res = await fetch('/api/admin/partner-access', { cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Unable to load partner access'); setAccounts(data.accounts); }, []);
  useEffect(() => { void refresh().catch(e => setMessage(String(e))); }, [refresh]);
  async function action(input: Record<string, unknown>) {
    setBusy(true); setMessage(''); setSetup('');
    try {
      const res = await fetch('/api/admin/partner-access', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...input, reason, identityVerified: verified }) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Review failed');
      if (data.setupToken) setSetup('/auth/activate#token=' + data.setupToken);
      setMessage(data.setupToken ? 'Password setup link created. It expires in 24 hours and can be used once. Share it with the verified contact using the correct partner app origin.' : 'Partner access updated.');
      await refresh();
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Review failed'); } finally { setBusy(false); }
  }
  return <main className="space-y-6 p-6"><h1 className="text-2xl font-bold">Partner access</h1><p>Complete the existing pharmacy, rider, lab or phlebotomist compliance review first. Invite the verified contact, then approve access. Partner readiness is checked at every sign in and protected request.</p><div className="flex gap-4"><a className="underline" href="/admin/careport">CarePort review</a><a className="underline" href="/admin/medreach">MedReach review</a></div><label className="block">Review reason<textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} className="block w-full border p-2" /></label><label className="block"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)} /> I have verified this partner’s identity and the contact’s authority to receive access.</label><form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void action({ ...Object.fromEntries(new FormData(e.currentTarget)), action: 'invite' }); }}><label>Role<select name="role" className="block border p-2">{['pharmacy', 'rider', 'lab', 'phleb'].map(r => <option key={r}>{r}</option>)}</select></label><label>Reviewed partner profile ID<input required name="actorRefId" className="block border p-2" /></label><label>Reviewed contact email<input required name="email" type="email" className="block border p-2" /></label><button disabled={busy || !verified || !reason.trim()} className="rounded bg-slate-900 px-4 py-2 text-white">Create password setup link</button></form><p role="status">{message.replace(/_/g, ' ')}</p>{setup && <div className="space-y-2 rounded border p-3"><label>Password setup path<input readOnly value={setup} className="block w-full border p-2" /></label><button className="underline" onClick={() => { setSetup(''); }}>Hide link</button></div>}<div className="overflow-x-auto"><table className="w-full text-left"><caption>Latest 200 partner access accounts</caption><thead><tr>{['Contact', 'Role / profile', 'Access', 'Password', 'Actions'].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{accounts.map(a => <tr key={a.id} className="border-t"><td className="p-2">{a.email}</td><td className="p-2">{a.role}<br />{a.actorRefId}</td><td className="p-2">{a.status}</td><td className="p-2">{a.credentialReady ? 'Ready' : 'Setup required'}</td><td className="flex flex-wrap gap-2 p-2">{['approve', 'suspend', 'reject', 'reset', 'revoke_sessions'].map(name => <button className="rounded border px-2 py-1" disabled={busy || !reason.trim() || (['approve', 'reset'].includes(name) && !verified)} key={name} onClick={() => void action({ action: name, accountId: a.id, version: a.version })}>{name.replace(/_/g, ' ')}</button>)}</td></tr>)}</tbody></table></div></main>;
}
