'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';

const DOMAINS = [
  ['identityPrivacy', 'Identity & privacy'], ['communication', 'Communication'],
  ['historyTaking', 'History taking'], ['iomtUse', 'IoMT use'],
  ['clinicalReasoning', 'Clinical reasoning'], ['safetyEscalation', 'Safety & escalation'],
  ['documentation', 'Documentation'],
] as const;

type Option = { id: string; userId?: string; displayName?: string; name?: string; email?: string; specialty?: string; lifecycleState?: string };
type Session = any;
function human(value: unknown) { const text = String(value || '').replace(/_/g, ' '); return text ? text.charAt(0).toUpperCase() + text.slice(1) : 'Request failed'; }
function lines(value: string) { return value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean); }
function localInput(value?: string | Date | null) { if (!value) return ''; const d = new Date(value); if (!Number.isFinite(d.getTime())) return ''; const offset = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - offset).toISOString().slice(0, 16); }

export default function SimulationControl({ defaultPatient }: { defaultPatient?: { id?: string; email?: string; name?: string } }) {
  const searchParams = useSearchParams();
  const requestedClinicianId = String(searchParams?.get('clinicianId') || '').trim();
  const [clinicians, setClinicians] = useState<Option[]>([]); const [clinicianId, setClinicianId] = useState('');
  const [patientQuery, setPatientQuery] = useState(defaultPatient?.email || defaultPatient?.name || ''); const [patients, setPatients] = useState<Option[]>([]); const [patientId, setPatientId] = useState(defaultPatient?.id || '');
  const [staffQuery, setStaffQuery] = useState(''); const [staff, setStaff] = useState<Option[]>([]); const [supervisorId, setSupervisorId] = useState(''); const [supervisorMode, setSupervisorMode] = useState<'OBSERVE'|'COACH'>('OBSERVE');
  const [scheduleMode, setScheduleMode] = useState<'availability'|'custom'>('availability'); const [slots, setSlots] = useState<any[]>([]); const [startsAt, setStartsAt] = useState(''); const [duration, setDuration] = useState(30); const [customReason, setCustomReason] = useState('');
  const [sessionNumber, setSessionNumber] = useState(1); const [scenario, setScenario] = useState(''); const [objectives, setObjectives] = useState(''); const [iomt, setIomt] = useState('Health Monitor\nNexRing');
  const [sessions, setSessions] = useState<Session[]>([]); const [status, setStatus] = useState<any>(null); const [selectedId, setSelectedId] = useState('');
  const [scores, setScores] = useState<Record<string, number>>({}); const [outcome, setOutcome] = useState('PASS'); const [strengths, setStrengths] = useState(''); const [developmentPoints, setDevelopmentPoints] = useState(''); const [summary, setSummary] = useState(''); const [recommendation, setRecommendation] = useState('');
  const [busy, setBusy] = useState(''); const [notice, setNotice] = useState<{ tone:'ok'|'err'; text:string } | null>(null);

  const request = useCallback(async (url: string, init?: RequestInit) => { const response = await fetch(url, { cache:'no-store', ...init }); const body = await response.json().catch(() => ({})); if (!response.ok || body?.ok === false) throw new Error(body?.error || `HTTP_${response.status}`); return body; }, []);
  const loadClinicians = useCallback(async () => { const body = await request('/api/admin/simulation/appointments?mode=clinicians'); setClinicians(body.clinicians || []); if (!clinicianId) { const preferred = body.clinicians?.find?.((item:any)=>item.id===requestedClinicianId)?.id || body.clinicians?.[0]?.id; if (preferred) setClinicianId(preferred); } }, [request, clinicianId, requestedClinicianId]);
  const loadSessions = useCallback(async (id = clinicianId) => { if (!id) return; const body = await request(`/api/admin/simulation/appointments?clinicianId=${encodeURIComponent(id)}`); setStatus(body); setSessions(body.sessions || []); setSessionNumber(Math.max(1, Number(body.createdCount || 0) + 1)); }, [request, clinicianId]);
  const loadSlots = useCallback(async () => { if (!clinicianId || scheduleMode !== 'availability') return; const from = new Date().toISOString().slice(0,10); const body = await request(`/api/admin/simulation/appointments?mode=availability&clinicianId=${encodeURIComponent(clinicianId)}&from=${from}&days=14`); setSlots(body.slots || []); }, [request, clinicianId, scheduleMode]);
  useEffect(() => { void loadClinicians().catch((e) => setNotice({ tone:'err', text:human(e?.message) })); }, [loadClinicians]);
  useEffect(() => { if (clinicianId) void Promise.all([loadSessions(clinicianId), loadSlots()]).catch((e) => setNotice({ tone:'err', text:human(e?.message) })); }, [clinicianId, loadSessions, loadSlots]);
  useEffect(() => { const timer = window.setTimeout(() => { void request(`/api/admin/patients?filter=all&pageSize=20&q=${encodeURIComponent(patientQuery)}`).then((b) => setPatients(b.items || b.patients || [])).catch(() => setPatients([])); }, 250); return () => window.clearTimeout(timer); }, [patientQuery, request]);
  useEffect(() => { const timer = window.setTimeout(() => { void request(`/api/admin/staff?state=ACTIVE&pageSize=50&q=${encodeURIComponent(staffQuery)}`).then((b) => setStaff(b.items || b.staff || b.rows || [])).catch(() => setStaff([])); }, 250); return () => window.clearTimeout(timer); }, [staffQuery, request]);

  const selected = useMemo(() => sessions.find((item) => item.appointmentId === selectedId) || null, [sessions, selectedId]);
  useEffect(() => { if (!selected?.assessment) return; setScores(selected.assessment.domains || {}); setOutcome(selected.assessment.outcome || 'PASS'); setStrengths(selected.assessment.strengths || ''); setDevelopmentPoints(selected.assessment.developmentPoints || ''); setSummary(selected.assessment.summary || ''); setRecommendation(selected.assessment.recommendation || ''); }, [selected]);

  async function createSession() { setBusy('create'); setNotice(null); try { if (!patientId || !supervisorId) throw new Error('Select a patient and supervisor'); if (!startsAt) throw new Error('Select an appointment time'); await request('/api/admin/simulation/appointments', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ clinicianId, patientId, supervisorId, supervisorMode, schedulingMode:scheduleMode, customSchedulingReason:customReason, startsAt:new Date(startsAt).toISOString(), durationMinutes:duration, sessionNumber, scenario, learningObjectives:lines(objectives), expectedIoMTs:lines(iomt) }) }); await loadSessions(); setNotice({ tone:'ok', text:`Simulation session ${sessionNumber} scheduled.` }); } catch(e:any) { setNotice({ tone:'err', text:human(e?.message) }); } finally { setBusy(''); } }
  async function lifecycle(appointmentId:string, action:string, extra:any={}) { setBusy(`${action}:${appointmentId}`); setNotice(null); try { await request('/api/admin/simulation/appointments', { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({ appointmentId, action, ...extra }) }); await loadSessions(); setNotice({ tone:'ok', text:`Simulation ${human(action)}.` }); } catch(e:any) { setNotice({ tone:'err', text:human(e?.message) }); } finally { setBusy(''); } }
  async function supervisorJoin(appointmentId:string) { setBusy(`join:${appointmentId}`); try { const body = await request('/api/admin/simulation/appointments', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ action:'supervisor_admission', appointmentId }) }); if (!body?.admission?.url) throw new Error('Supervisor admission unavailable'); window.location.assign(body.admission.url); } catch(e:any) { setNotice({ tone:'err', text:human(e?.message) }); setBusy(''); } }
  async function saveAssessment(finalize:boolean) { if (!selected) return; setBusy('assessment'); setNotice(null); try { await request('/api/admin/simulation/appointments', { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({ appointmentId:selected.appointmentId, action:finalize?'finalize_assessment':'save_assessment', assessment:{ domains:scores, outcome, strengths, developmentPoints, summary, recommendation } }) }); await loadSessions(); setNotice({ tone:'ok', text:finalize?'Assessment finalized.':'Assessment draft saved.' }); } catch(e:any) { setNotice({ tone:'err', text:human(e?.message) }); } finally { setBusy(''); } }
  async function approve() { setBusy('approve'); try { await request(`/api/admin/simulation/clinicians/${encodeURIComponent(clinicianId)}/approve-real-patients`, { method:'POST', headers:{'content-type':'application/json'}, body:'{}' }); await loadSessions(); setNotice({ tone:'ok', text:'Real-patient approval recorded.' }); } catch(e:any) { setNotice({ tone:'err', text:human(e?.message) }); } finally { setBusy(''); } }

  return <div className="grid gap-5 xl:grid-cols-[440px_minmax(0,1fr)]">
    <section className="space-y-4 rounded-3xl border bg-white p-5 shadow-sm">
      <div><label className="text-xs font-black uppercase text-slate-500">Clinician</label><select value={clinicianId} onChange={(e)=>setClinicianId(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Select clinician</option>{clinicians.map((c)=><option key={c.id} value={c.id}>{c.displayName || c.email || c.id}{c.specialty ? ` · ${c.specialty}`:''}</option>)}</select></div>
      <div><label className="text-xs font-black uppercase text-slate-500">Simulation patient</label><input value={patientQuery} onChange={(e)=>setPatientQuery(e.target.value)} placeholder="Search onboarded patient" className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/><select value={patientId} onChange={(e)=>setPatientId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Select canonical patient</option>{patients.map((p:any)=><option key={p.id} value={p.id}>{p.name || p.displayName || p.contactEmail || p.email || p.id}</option>)}</select>{defaultPatient?.id ? <p className="mt-1 text-[11px] text-slate-500">Configured simulation patient is a default only; the selected canonical patient remains authoritative.</p>:null}</div>
      <div><label className="text-xs font-black uppercase text-slate-500">Supervisor</label><input value={staffQuery} onChange={(e)=>setStaffQuery(e.target.value)} placeholder="Search active staff" className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/><select value={supervisorId} onChange={(e)=>setSupervisorId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Assign supervisor</option>{staff.map((p:any)=><option key={p.id || p.userId} value={p.id || p.userId}>{p.name || p.displayName || p.email || p.id}</option>)}</select><div className="mt-2 flex gap-2">{(['OBSERVE','COACH'] as const).map((m)=><button key={m} type="button" onClick={()=>setSupervisorMode(m)} className={`rounded-xl px-3 py-2 text-xs font-black ${supervisorMode===m?'bg-slate-950 text-white':'border bg-white'}`}>{m==='OBSERVE'?'Observe':'Coach · mic only'}</button>)}</div></div>
      <div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setScheduleMode('availability')} className={`rounded-xl px-3 py-2 text-xs font-black ${scheduleMode==='availability'?'bg-indigo-600 text-white':'border'}`}>Clinician availability</button><button type="button" onClick={()=>setScheduleMode('custom')} className={`rounded-xl px-3 py-2 text-xs font-black ${scheduleMode==='custom'?'bg-indigo-600 text-white':'border'}`}>Controlled custom</button></div>
      {scheduleMode==='availability'?<div><label className="text-xs font-black uppercase text-slate-500">Available slot</label><select value={startsAt} onChange={(e)=>{const slot=slots.find((s)=>s.start===e.target.value);setStartsAt(e.target.value);if(slot?.durationMin)setDuration(slot.durationMin);}} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Select current availability</option>{slots.map((s)=><option key={s.start} value={s.start}>{s.localTimeLabel || new Date(s.start).toLocaleString()} · {s.durationMin} min</option>)}</select></div>:<><div><label className="text-xs font-black uppercase text-slate-500">Custom date/time</label><input type="datetime-local" value={startsAt} onChange={(e)=>setStartsAt(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></div><textarea value={customReason} onChange={(e)=>setCustomReason(e.target.value)} placeholder="Reason for controlled custom scheduling" className="w-full rounded-xl border p-3 text-sm"/></>}
      <div className="grid grid-cols-2 gap-3"><label className="text-xs font-black uppercase text-slate-500">Session #<input type="number" min={1} max={99} value={sessionNumber} onChange={(e)=>setSessionNumber(Number(e.target.value))} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label><label className="text-xs font-black uppercase text-slate-500">Duration<input type="number" min={10} max={120} value={duration} onChange={(e)=>setDuration(Number(e.target.value))} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label></div>
      <textarea value={scenario} onChange={(e)=>setScenario(e.target.value)} placeholder="Scenario" className="w-full rounded-xl border p-3 text-sm"/><textarea value={objectives} onChange={(e)=>setObjectives(e.target.value)} placeholder="Learning objectives — one per line" className="w-full rounded-xl border p-3 text-sm"/><textarea value={iomt} onChange={(e)=>setIomt(e.target.value)} placeholder="Expected IoMTs — one per line" className="w-full rounded-xl border p-3 text-sm"/>
      <button type="button" disabled={busy==='create'||!clinicianId} onClick={()=>void createSession()} className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40">{busy==='create'?'Scheduling…':'Schedule simulation'}</button>
    </section>
    <section className="space-y-4">
      {notice?<div className={`rounded-2xl border p-4 text-sm ${notice.tone==='ok'?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-rose-200 bg-rose-50 text-rose-900'}`}>{notice.text}</div>:null}
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Readiness</h2><p className="text-sm text-slate-500">Finalized PASS sessions only.</p></div><div className="text-right"><div className="text-2xl font-black">{status?.passCount || 0}/3</div><div className="text-xs text-slate-500">distinct qualifying passes</div></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-500" style={{width:`${Math.min(100,((status?.passCount||0)/3)*100)}%`}}/></div><button type="button" disabled={!status?.readyForApproval||busy==='approve'} onClick={()=>void approve()} className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:opacity-40">Approve real-patient access</button></div>
      <div className="space-y-3">{sessions.map((s)=><article key={s.appointmentId} className={`rounded-3xl border bg-white p-5 shadow-sm ${selectedId===s.appointmentId?'ring-2 ring-indigo-200':''}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><button type="button" onClick={()=>setSelectedId(s.appointmentId)} className="text-left"><span className="text-xs font-black uppercase text-indigo-600">Session {s.sessionNumber||'—'} · {human(s.status)}</span><h3 className="mt-1 text-lg font-black">{s.patientDisplayName||'Simulation patient'}</h3><p className="text-sm text-slate-600">{new Date(s.startsAt).toLocaleString()} · {s.supervisor?.name||'Supervisor'} · {s.supervisor?.mode||'OBSERVE'}</p><p className="mt-1 text-xs text-slate-500">Assessment: {s.assessment?.status?`${human(s.assessment.status)}${s.assessment.outcome?` · ${human(s.assessment.outcome)}`:''}`:'pending'}</p></button><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void supervisorJoin(s.appointmentId)} className="rounded-lg border px-3 py-2 text-xs font-bold">Join as supervisor</button><button type="button" onClick={()=>void lifecycle(s.appointmentId,'extend',{extensionMinutes:15})} className="rounded-lg border px-3 py-2 text-xs font-bold">+15 min</button><button type="button" onClick={()=>void lifecycle(s.appointmentId,'no_show')} className="rounded-lg border px-3 py-2 text-xs font-bold">No-show</button><button type="button" onClick={()=>void lifecycle(s.appointmentId,'cancel',{reason:'Cancelled from Simulation Control'})} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Cancel</button></div></div></article>)}</div>
      {selected?<div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Private supervisor assessment · Session {selected.sessionNumber||'—'}</h2><p className="mt-1 text-sm text-slate-500">Scores are private readiness evidence. Finalization is blocked until the scheduled session has ended.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{DOMAINS.map(([key,label])=><label key={key} className="rounded-2xl border bg-slate-50 p-3 text-sm font-bold">{label}<select value={scores[key]||''} onChange={(e)=>setScores((current)=>({...current,[key]:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border bg-white px-3 py-2"><option value="">Score 1–5</option>{[1,2,3,4,5].map((n)=><option key={n} value={n}>{n}</option>)}</select></label>)}</div><select value={outcome} onChange={(e)=>setOutcome(e.target.value)} className="mt-4 w-full rounded-xl border px-3 py-2 text-sm"><option value="PASS">PASS</option><option value="NEEDS_DEVELOPMENT">Needs Development</option><option value="REPEAT_REQUIRED">Repeat Required</option></select><div className="mt-3 grid gap-3 sm:grid-cols-2"><textarea value={strengths} onChange={(e)=>setStrengths(e.target.value)} placeholder="Strengths" className="rounded-xl border p-3 text-sm"/><textarea value={developmentPoints} onChange={(e)=>setDevelopmentPoints(e.target.value)} placeholder="Development points" className="rounded-xl border p-3 text-sm"/><textarea value={summary} onChange={(e)=>setSummary(e.target.value)} placeholder="Assessment summary" className="rounded-xl border p-3 text-sm"/><textarea value={recommendation} onChange={(e)=>setRecommendation(e.target.value)} placeholder="Recommendation" className="rounded-xl border p-3 text-sm"/></div><div className="mt-4 flex gap-2"><button type="button" disabled={busy==='assessment'} onClick={()=>void saveAssessment(false)} className="rounded-xl border px-4 py-2 text-sm font-black">Save draft</button><button type="button" disabled={busy==='assessment'} onClick={()=>void saveAssessment(true)} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Finalize assessment</button></div></div>:null}
    </section>
  </div>;
}
